apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - pvc-util.yaml
  - cloudflaredns/ks.yaml
  - cyberchef/ks.yaml
  - it-tools/ks.yaml
  - litellm/ks.yaml
