# ---
# apiVersion: helm.toolkit.fluxcd.io/v2
# kind: HelmRelease
# metadata:
#   name: qbit-proxy
#   namespace: media
# spec:
#   interval: 15m
#   chart:
#     spec:
#       chart: qbittorrent
#       version: 24.0.1
#       sourceRef:
#         kind: HelmRepository
#         name: truecharts
#         namespace: flux-system
#       interval: 15m
#   postRenderers:
#   - kustomize:
#       patches:
#         - target:
#             version: v1
#             kind: Deployment
#             name: qbittorrent
#           patch: |
#             - op: add
#               path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
#               value: 1
#   timeout: 20m
#   maxHistory: 3
#   install:
#     createNamespace: true
#     remediation:
#       retries: 3
#   upgrade:
#     cleanupOnFail: true
#     remediation:
#       retries: 3
#   uninstall:
#     keepHistory: false
#   values:
#     credentials:
#       s3v3:
#         type: s3
#         url: "${S3_MINIO_URL_V2}"
#         bucket: "${S3_MINIO_BUCKET_PREFIX}-v2-{{ .Chart.Name }}"
#         accessKey: "${S3_MINIO_KEY_ID_V2}"
#         secretKey: "${S3_MINIO_SECRET_KEY_V2}"
#         encrKey: "${S3_MINIO_SECRET_KEY_V2}"
#     # service:
#     #   proxy:
#     #     enabled: true
#     #     ports:
#     #       gluetun:
#     #         enabled: true
#     #         port: 8888
#     #         protocol: "http"
#     #         targetPort: 8888
#     # workload:
#     #   qbitportforward:
#     #     enabled: true
#     #     # QBT_USERNAME: "${ADMIN}"
#     #     # QBT_PASSWORD: "${ADMIN_PASSWORD}"

#     qbitportforward:
#       enabled: true
#       # QBT_ADDR: ${QBT_ADDR}
#       # QBT_USERNAME: ${QB_ADMIN}
#       # QBT_PASSWORD: ${QB_ADMIN_PASSWORD}
#     service:
#       proxy:
#         enabled: true
#         ports:
#           proxy:
#             enabled: true
#             port: 8888
#             protocol: "http"
#             targetPort: 8888
#     addons:
#       vpn:
#         type: gluetun
#         killSwitch: true
#         excludedNetworks_IPv4:
#         - 192.168.0.0/16
#         env:
#           VPN_TYPE: wireguard
#           VPN_SERVICE_PROVIDER: protonvpn
#           #WIREGUARD_ENDPOINT_IP: ${WG_ENDPOINT_IP}
#           #WIREGUARD_ENDPOINT_PORT: ${WG_ENDPOINT_PORT}
#           #WIREGUARD_PUBLIC_KEY: ${WG_PUBLIC_KEY}
#           WIREGUARD_PRIVATE_KEY: ${WG_PRIVATE_KEY}
#           #FIREWALL_VPN_INPUT_PORTS: ${WG_FIREWALL_INPUT_PORT}
#           #WIREGUARD_ADDRESSES: ${WG_ADDRESSES}
#           HTTPPROXY: "on"
#           FIREWALL_INPUT_PORTS: 10095,8888
#           SERVER_COUNTRIES: ${SERVER_COUNTRIES}
#           #SERVER_CITIES: ${SERVER_CITIES}
#           #SERVER_HOSTNAMES: ${SERVER_HOSTNAMES}
#           HTTPPROXY_LOG: "on"
#           HTTPPROXY_LISTENING_ADDRESS: :8888
#           #VPN_PORT_FORWARDING_UP_COMMAND: ${VPN_UP_COMMAND}
#           VPN_PORT_FORWARDING: "on"
#           PORT_FORWARD_ONLY: "on"
#           #VPN_PORT_FORWARDING_STATUS_FILE: /tmp/gluetun/forwarded_port
#           # VPN_PORT_FORWARDING_LISTENING_PORT: 6881
#     # ingress:
#     #   main:
#     #     enabled: true
#     #     hosts:
#     #       - host: qbit-proxy.${DOMAIN_0}
#     #     integrations:
#     #       certManager:
#     #         enabled: true
#     #         certificateIssuer: domain-0-le-prod
#     ingress:
#       main:
#         enabled: true
#         ingressClassName: internal
#         hosts:
#           - host: qbit-proxy.${DOMAIN_0}
#             paths:
#               - path: /
#                 pathType: Prefix
#         tls:
#           - hosts:
#               - qbit-proxy.${DOMAIN_0}
#             clusterIssuer: domain-0-le-prod
#         integrations:
#           traefik:
#             enabled: false
#           certManager:
#             enabled: true
#             certificateIssuer: domain-0-le-prod
#     persistence:
#       config:
#         volsync:
#           - name: config2
#             type: restic
#             credentials: s3v3
#             dest:
#               enabled: true
#             src:
#               enabled: true
#       plex-media:
#         enabled: true
#         existingClaim: plex-media-pvc
#         mountPath: /mnt

---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent-proxy
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: qbittorrent
      version: 24.0.1
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  # postRenderers:
  # - kustomize:
  #     patches:
  #       - target:
  #           version: v1
  #           kind: Deployment
  #           name: qbittorrent
  #         patch: |
  #           - op: add
  #             path: /spec/template/spec/containers/1/resources/limits/truecharts.org~1tun
  #             value: 1
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    qbitportforward:
      enabled: false
      QBT_USERNAME: "${ADMIN}"
      QBT_PASSWORD: "${ADMIN_PASSWORD}"
    # service:
    #   proxy:
    #     enabled: true
    #     ports:
    #       proxy:
    #         enabled: true
    #         port: 8888
    #         protocol: "http"
    #         targetPort: 8888
        # type: "ClusterIP"
    service:
      proxy:
        enabled: true
        ports:
          proxy:
            enabled: true
            port: 8888
            protocol: "http"
            targetPort: 8888
    addons:
      gluetun:
        enabled: true
        container:
          # excludedNetworks_IPv4:
          # - 192.168.0.0/16
          resources:
            limits:
              truecharts.org/tun: 1
          env:
            VPN_TYPE: wireguard
            VPN_SERVICE_PROVIDER: protonvpn
            #WIREGUARD_ENDPOINT_IP: ${WG_ENDPOINT_IP}
            #WIREGUARD_ENDPOINT_PORT: ${WG_ENDPOINT_PORT}
            #WIREGUARD_PUBLIC_KEY: ${WG_PUBLIC_KEY}
            WIREGUARD_PRIVATE_KEY: ${WG_PRIVATE_KEY}
            #FIREWALL_VPN_INPUT_PORTS: ${WG_FIREWALL_INPUT_PORT}
            #WIREGUARD_ADDRESSES: ${WG_ADDRESSES}
            HTTPPROXY: "on"
            FIREWALL_INPUT_PORTS: 10095,8888
            SERVER_COUNTRIES: ${SERVER_COUNTRIES}
            #SERVER_CITIES: ${SERVER_CITIES}
            #SERVER_HOSTNAMES: ${SERVER_HOSTNAMES}
            HTTPPROXY_LOG: "on"
            HTTPPROXY_LISTENING_ADDRESS: :8888
            #VPN_PORT_FORWARDING_UP_COMMAND: ${VPN_UP_COMMAND}
            VPN_PORT_FORWARDING: "on"
            PORT_FORWARD_ONLY: "on"
            #VPN_PORT_FORWARDING_STATUS_FILE: /tmp/gluetun/forwarded_port
            # VPN_PORT_FORWARDING_LISTENING_PORT: 6881
    ingress:
      main:
        enabled: true
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod
        tls:
          - hosts:
              - qbit-proxy.${DOMAIN_0}
            clusterIssuer: domain-0-wildcard
        hosts:
          - host: qbit-proxy.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix