apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: syncthing
  namespace: flux-system
spec:
  interval: 10m
  path: clusters/main/kubernetes/apps/utilities/syncthing/app
  prune: true
  sourceRef:
    kind: GitRepository
    name: cluster

