apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Z0STvZ5aW5EaVnkUSUTgJzEoVW2P6IAHLrQkCLxGQaZz9y00hTKMRhUrjwbAYeZ327ApAH9FV/3RpZ8pDytw015Pwej6xWsUsJWs1SHShEsbzU8yqRBZRM10HCDpJ2TM2rlTxkxJJLjmb9Lla+C+EIuubocra+jtKvIRjNuQP6K2GQiyVDZxMn99ba6/MvCJ0u4vjnFG+XfjB+1bYLehinpmmjPLbu7KhjWan4eUXF4KcIQSpZBDfG3Ox3P1sSEX98V/6poiIIWcXz41zk217bIu8mP2zniE0IBFVOwRSEcEAgPUGz/V1W/3Zc2i0Qe7ys9YCq4/Eoro31Kzb3QHGC3jXYGH8sRv51IjJm/5cOmlQ5zkinPxzRT4tgOJs1Lk,iv:nrjlIJBuj58oQy4szoDzOrF0qjMc8JOj7302HADHjz0=,tag:L9I3d8hTvJPTZxJKRoZvfw==,type:str]
    identity.pub: ENC[AES256_GCM,data:n4MLqWC4vtSoPs4T2yukhBFxED4r4Lqw/uG5AsEJh2IBNJBH9JEGu2DlA3J3A63r9l15lTrTYlA8V39I2W9JLZv8oKVd6EHw2DL4Mp5UGgzjTb6JK2xwz3jfP3k6yyaxZ4r2I7QrokKvPR/i8OscyOx36HFFdxmbxgPVWqNiZORILb3sos/bIou4rNHUD5VL2NyAzzVHPsDQCxteGOHpKLOeqLUPeTaDk7bnu/+dYHYU8PVXuQ4jfAFUrgoVRR+2pjo7r6oBjBoEp2ub/Q==,iv:fCCjFnJqo1RXOpcdWx1EV+sstbHUGtGcry4QForefGw=,tag:fbJGpKw58I++c4QIRoh58A==,type:str]
    known_hosts: ENC[AES256_GCM,data:lVoqInE67sNhS0CCYATBRDwEvfd18fAVghRzdbGbA1XnNA5fPpqK2VkQ0sx3su1/SIl4s66iPHLecGGSJH1O/O+k/shPUtiXkJ5XJapyz+YDwuVY+xjGbs90CqzeEapA7vLdrHTD9T1kyW7lBPEVASXXok1DCbTvZAtpdIvOmYtoY6hLl/XYsM0YzojeIyUoQW2X1vusz+jhjVz8gFseni3QG4hd0TgND+9+,iv:C4Bn6AELAY2Yj16s+D2cNRjJIGbch2h31XQUL81mmxg=,tag:iNmJpc1lqTSJnytbnIG5Og==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBkd0dUSE84TlVpMi9YNDJI
            QjVnQVVoVnE3d25TQkNzdkZ1QTdJOVlLWmkwCkxkSUVmeUE1bmJjL0hVN295VjRY
            VUp2QVRqbTlPN2NrbWgwRG1rWjJwWHMKLS0tIFVNTVdzUk8wNDlSNGlITmF4NkpO
            MVdIbjB4R2w4RG9oNkU4NFNxdXplalUKhOU3vub17Z+dUEYNQDI/8fZhE9uxDXZ2
            X9ME4CtfpPV/HPROMo5XVeqdsSz/akcGXJiz23eXvIr9JgqJ+ndZ2w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:02:31Z"
    mac: ENC[AES256_GCM,data:5cszNMXrxM9y7VFkiywpnEqhYuRqByJuwf/AbW9GFhUnm43fCpA11YUzqSCnE0iCWx+9dJxNovMpBv3e2gpVS1YpnBERSd1JlJD7aCNkSkTa6eB+hm0nWtYRGpNCeEwxH4T5zZF7CMjzT1IACJayIABjO8VYGaVes7ZaTlrVDjg=,iv:edbnwzOqz+5KIkmlqaK4M73RtboNhvbtQFMb/mbdeIU=,tag:MB3mKY4Gfi4gQ7QbQ0N0Zg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
