apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:FueLMaQNF1yRd2mHX6gHwtZime1UKNuSyjCQhqcOY8Dec+tb/A3ntBo+G3ivILtWq16Yl1GO9Wu2scciLhsZvCQYeOyJKT711cHMLEpSVxJfjv5j/zM7UbTFMobDsi4E7jta/RQaGbJKkB5fWchtUGFDQV0gWE4GegOzNNjFAyTVx8c7edrPpwLZnqoyxODBRyFzBIfvNoVFkDF3ArKIQQUJiYD4C3ToZ1EXSla8WT2Dwr7NDvWmLGtcMvlkllGxIM6Km1sLFCFUey5a5twUkdL5NFsYArEO2zWa9HVEoyrFHk+OaygOMOTeGN/0z6SED7fM3Pp4IdvDb/5lOLOKyNshwkxrhIByhM6GYmEAo5o/KUTILC3m/j8VLzkz4di6,iv:GeGPGN+bkb1SBFOxx1I8zefUPEmjw2EZMntOr4qaTH8=,tag:tO6NnoOjcclQE/PTE/wcOw==,type:str]
    identity.pub: ENC[AES256_GCM,data:SHTD7jcx8ndg5tOPRefmse1/U7QdAmUFHhSpNh54OFNr3HTu/8l+rKlSGPE09lZDfOuQHpWlbw520N3VeI/h0L3qd8a80WpsT05jpbcFBxRM1DGciyjUWhs+9LjjHBcWUzHyokAM/JcKY3JGwXtAovXzMQgoHSRkKMILbfMF6eESwY0C4Ige6UWMNo494l6KGiuMThYtScJlNnFHjVCgwUQRbgfsQwdkyRsBrbNP8V4dAveDEbEzZirvdyxK4j3EUCOy6bV51F9y3na4Tg==,iv:7zeQ+MbwLw/Jj1W2rbE1Cj1AfUIIvQw58IsTvYQvf+k=,tag:7j33r04ggSPJxVnk1DRx4w==,type:str]
    known_hosts: ENC[AES256_GCM,data:19U/P/JdFVFMwvRZ/t26Ttyk9IogrKgPymlkTTP1od+QiDzbRLdtV19JsK6k03TggCEHAGcUh1GzH6eNvQk7lRzhVj3CTw+EtGOK234jRXOjiDN5vFrLfKOLU/y9Gu5F7Ap0b3YfVMKiIj3g403OZ7l22yl9/H2VTESJoHlOerPg5s/Osqoy3DLKoTxFlm4bTaDGxj0PMG9GTn/z9QkHUIajBk9t/vQsbCzC,iv:OPygKol7JhkeyaowNie2MiFSvaSUbYNZoy/OelQrxbE=,tag:004Q0aoq5iMdrTTfLWuu5g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBzSHo0cy9pMUNKT00zSjQw
            RGJwMTk0Zzk1MUxVa2h5bEpOcFkvR0NUM2tNCjRjcEw5RXhTMW1NRENJSi9xQW81
            SzN5K2RjYnNROFQ1Q0pKSi9NKzNBVlEKLS0tIHhyMVR2ZWtFem96K08wSXB3TFZH
            bHRpWm50NUJLdHZ2ZHJHU3h5a3huRU0KBbmDssnp7pER3m8OXR2eolJCZwOIDcCp
            by2U1fCXHKQj/KftePEJLDb+pcP4T2QynRgLZW7JZIabULH1nYfvzw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T01:23:00Z"
    mac: ENC[AES256_GCM,data:C6o6Aa3h2krkRu3HIWHcQL+K/FJeXcbku3yIXnPbAtbk39Gzb1ci63RBt4N74UcbM/iX7aJGpGWoSpYouYzHVX77Co55kOy/X0krPa4UO5WnyyxxB4yk1JNboHJSAmvnN6vhSk1Avd+aHP++XaqlnFLLDdYYw3ar6kjD0EPYmVY=,iv:/e13H/LBCEQTxJKGP8CLv0sXQhJEDQO7VVRvvcu2NtY=,tag:T+h/5GmEy2vw7h6Y8Qxkhw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
