apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Jvg27HCqtLARnWTO19zo5IbA21SCyW8j5HFg5q2Zo5qu8kYbpKKHckSJNblActUBzLmyrBEr2D9HizCKhykAFWJdnAj8Cx/yFckCMoP8hmyyygqlqBMPPFXB8ejzbUkXBviNmLvr/FlbA4GNuwZ+Ifidcm67wc/wksL2o6bVWvG3d8FtnVxEjwlP64ORtCgpM+Ujwlzo4OpEnuoLDfWlcSZ7o/VQRuVC1GbZT69KIdnc91XbnpLR1Ms5bJ0eaxzSyo7CazmykheSl+cmAO8Cr+hCVqoJH4uxgA/da+wXhck7C0Pu81KDTYAF1OJG/24N59twXcqFX0zmDB+PFjyT+iImJegJ0lgOnsqW8Evtxn2krTalDfMscpJYEkHGW0q5,iv:DRVQSRiOeB/QWADfXqD6P7+hB+cp9c+ZTrZW9riCJYI=,tag:XROcSM7iYl6ptev/Stjyzw==,type:str]
    identity.pub: ENC[AES256_GCM,data:3ahalXleurbfI+AjxSVTsXxnhz+EW9S/r3QUj0evkXKNyaNi3lRIIMt/Rle5oqU1GwwOvlcw+XzJZp15xqVRfmkXr4R/ETlK8hM+BI8PZDCrWgDQI2lnUXveImtuqxMwE3mObCR2Q3S0GFRGs4qHkuYuSYMBmaUajd20vcxyQ3GnEvaU+y9N7onqBgX4ywabgc4UECKPQJUaKLUAwFAs4KERLzAxqQPZvWwZxQETbXUJ8WhP/duUbKuVtGYKmdT+5zAJmpGvcMbZ2BNu9g==,iv:EqBlPV2e37d9CT/401gOGMRqYpV4WyLLFTJmp10nd5M=,tag:4T0bnNZYgXo679lDt3IzIw==,type:str]
    known_hosts: ENC[AES256_GCM,data:KYYE4lHo95gsQFyRryMlJKdR7HU78Oz0kjDI4KQX7NwtWeJtDPPv67Ig7YUVLNx2eCy5jDgjnZVuvPftmtt8/crBuwDLCo/WNUS9ZywX6C94Q7gKJooJSrjwFzH3g7Or0tl80ShClvEuuxQB6wFXnRCKovL3MRpT57pZLQ+1rN8C3jljr4hqt3hVhJn8HDokCte6UWWR4JiuRBQ8Az2cSGdpQjeUaTU+Tvc1,iv:VmuCb59H9YTEMrZ5RSp8SzPXZgt2wuT8gfmw/ivoWAc=,tag:jk75ZJ3f/uMuRy/2xXrG2Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3MDF6Smk3a1FTSm9EV2tK
            ak5oSkdMVmRzMTc4SldZK1RZczF6TkVrNmdBCmFFV2NJWU9EWTAvK0JUcURvc0s0
            UFZOOGV1QkxXSDM4eGZ6QlJBcENwZVUKLS0tIGpVQ1dqdldxTW9FRVI5OUFRazBo
            OURvMUpuVXUvT3VhV0NKWHdaZy8wSkUKIr9TmQy05DIsq1tVo6AOvF6jPJZggLuo
            EijqqJMxqu5Kcc+puJxPcQZJILgMwJVHHh7/kIk2MQnprii70JfuOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T19:40:52Z"
    mac: ENC[AES256_GCM,data:ceUW5kbLxcYh3ZmsNvZSGnUAwQsxxDZfZWkr2yR/I+jEOSA0TnEpKNc+o9Znk+J+Kw7lF3jUrbCF/cBzdZZ2smHES3iI4wxyxL1xvHoVdFSzIpQdS6Y+5irFaN0foiHATXMK2BuZF0gsP3lpomU5H2wnf2EvjyiLPfxFPWkPADw=,iv:C1LSxQ3cL4RlqUAD3fZ4xEyT2cOB3X1deyR5dckJXxw=,tag:/+SRYPN1rUMrciCsPcHWhw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
