apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Txg+yvA4hRv0hiGywhA30weBG6i43ACXQMGCrIvkkWLEB81aXUyXEFy1opkT4Jk/hMuDfH2KEF6MgC3a3rmo9+cmQt0Je/4+XnLZGu7MPLD+/C3C6KxUZdw97/n/+1GK0ibe2Trv7uMC9aTKer8SZL9ZXhEuCaeZxdwCraBMdfdoGvMakZ0BevUBfLbwoKCYx00kNdiThEB8PLm41nMianbYYAXk+aSsiNoYUQ5+WTwutt377bMBOIPE90Eq/+aNSNtHamoMrXxxSrngTPrk4qAQEk6/3TOcepMB9pjKow5O751TGi19ZF6UQ6xhzA0SD7dDEIWGGAObLmkt5K1KXQmGZOOO8/QJcucr5t57+Txma3JOhNMm75fjNEmNIgkG,iv:V5NHsW6v8Tv+//0JnEYvyfPXbF3qygem+MXeisQWAbY=,tag:Sh53qepO1kdQmmS/B1JRhg==,type:str]
    identity.pub: ENC[AES256_GCM,data:CxHriTzaUk1j7IW14B4B1Z3v/uhI6YSNLCRIk3pZI3ro7cmQbk6GVmkSSDZIWJe4mT6J0LYwc2ehjNbZFGLHfAU8zsMGvfoVamqrf94YUhLcmVMHfMSVYgB1MszarL/jF7AC8VpZZtYz0zU5ARjE+Y3R7lv3WgQJDOE7BGpShjwW67CnDYuSsAV8phbwLBxp8lo3CAwsJQXN7Zths4JDiBC/Kok4eFAyNmjVQsWwgmsQYq/nORnSpLYaxsM0J9UB/nQ/YigH2GHFlZ3lLA==,iv:6Uy+t2EH0WJwBkagjWGHdmmbZWjt39qgiIKZkdxiNcQ=,tag:6Ze6CYOqeRMRQBPl8O9NRw==,type:str]
    known_hosts: ENC[AES256_GCM,data:JtHyQ/O/9nblW2EVIxhceCiaNWLasRPOUUEDMhDPG4egrZdDfohiWtfnQSCZ/dgf85E5cZtUcF+sbGaRT7kCAiX28qwJ1QV/gQNFQZ1AXj4pDz0PknaTNZ+r4fKPkxdyVzgYKwL+FMljSfchW5cBcjdl4DJW+KbPvwcm7JNH2sEKXQbJn+I1RmXin3Ik3RBBUpTN3ygbEaFUP/gf+Gkh1MB3LnDgVK1qN7eW,iv:9g4lpXbEF9OTKjY5i1vOu9C6poOfhmo9oTToV3nW7tA=,tag:Q1tRSD9OTr2geEM9FJbP7A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5NmQ0bXdMVy82R3Evb2xh
            NTN5N1lJTjZ5ejRwQ1g2SWZzNkdUckxtT1dNCjArMllpS2JQZGRrK1hpNVh4alhS
            UEI1N3dJQk5BcUxTRDkxZG8yU0xCVFEKLS0tIC9ZdWUrays4bDQrdEFwUXMxZFBt
            aVVzUURQcVovanRodG03UmZkRFhIbjgK+g7DTF5h8sN4zZic8xbPkzLIdwkMMD9f
            gmjL6B3jUXwXtt/kWsTLHBMuySQlXxYyVqWhTZIndYHpC5SuSx9PKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:33:59Z"
    mac: ENC[AES256_GCM,data:WjPjS8EEhNoh0yIsvIE7PFjAuURtTUdoWr/XPptyulSay+Q89wEtknRcBoOOx0kYlp9WYra8m0WM4J3avS5nBLdiJ1899GVBQA9SEuEQm0ow4XyFQKQgqaRKfXZAuV3kiPyStAi/Une48hUBpTZPk0Ye4AfliTeXGvjmgiIktjs=,iv:nu//+yoTtpNjDmH7WYZGwL5eK1BmoCfXrlkTRT0wJjI=,tag:YhXg+TJBLh8cX+dHx3K+Cg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
