apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:VYjnrPB1O1L3pwm9dVqtDgynKaN/H7ickdZBjqLJSv5sJDxVR7Hium7FvMgQhYq1puBV0nDCVJt5d16xCXxfb1dtNNcjX4+Wu1+k6mVLKlkRG+WL/nKrh/jcqwVg9KFZoe36/OyaxFGcxkr6NeAfYaeF1mDcTYob3/Zld3q1Qjm/DIMw4JGZri7NXchWgUaAAawXuwGAZWjQFPZ0gjBZEQPygmsscpm88ehQR08jOXD23/pFiYNaEVnITrZ3RVPes1EI2E7+7ypmhBYP/cwWcs6jkKPjJkQ1SW8dbyJD2OhP4EkgoPR+0USDY6lCnmyGJ3QQX4l5PZFml4a63XW3/r7s7M+LL5p4BcumudkGreiwmURNkGDLERSs7OpOK7bb,iv:R+7JioWy0o78s3QcSoKwurz6J0Covt8DKYzsMVkziC0=,tag:rQoNAwllys8S8D6oSA6qmg==,type:str]
    identity.pub: ENC[AES256_GCM,data:8P9D4wcFdjWsPkQBTnmsA/XJzCinIne0MX6ttBfpViWwMHkcnZc3+dQ/vMt9PKLs7LcVP/URtt+KsLApLkTMYLBed/cILbKqCyEzItXLvyMkLrQxuE3DGyUGzNDw/FYAD5NLxTgG80nIsyxqIze4mB/iop5GPPSG3Bl1TQ3wiJEH/Fs1M4ny+2XabrM9bKHUIYUNXkZa5loT9uaUwUHjGzDWfP+ZMgs5oF9nNLYlMcr7bcpi3kGccrAk077VfLsx9lzzn5IJ9caFMUFGeg==,iv:WOCr7qKhztTRlHqh4eQ1HUHDR+8a+BBnyCiupS3ZscU=,tag:9HH6a4ic9OU3z1qutha0BA==,type:str]
    known_hosts: ENC[AES256_GCM,data:cxyXso99q6O9t7FIFB8cQikYis5haJeALs3sWEOCCoNFD9Inl9tUGVHkpr5lAVFDzSL6K9vwwYQqEbIyOQ8dYYoK+tuatAu8DYYvl6Xcd98jcUvBLJkY9TVmPIixcQ2TwT9ycL+rEGB70yHU2DK4Tw5GLFXuDV3TQHkV8SNj3zCRcPrS60uqXauDzcPWSP17RO/p2a4zxvSl/RqHDVRYs6yMDKF+wCAkEGAP,iv:M1Ml5e7hu/FLJxC13k1koqYKxO6zfyLZEhi3f4MXdJc=,tag:PRSGc5eYBc0CzZwX471NUw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1MUV0Z0ZsVTg2Y2pVVmRk
            QjM3MnduZUlUbHY5S0hialdJWDZkWWlrdTBzCjVRZkZkNnZ4YkZkTytVdVNFR0hZ
            V3N1OGwvclNnT1NjOXZKeGlTR1ZnUFEKLS0tIHNKN09ocWg2SjdlQWhaOVNyc1py
            WDZwQTlHSmk3cDBVWlFwbW81aUFGOWcKEUrdlfJyzO4ewT27eQBO/kqw4VvSUUqg
            3a/e6JeuZGp1kHTpPIMF+69P79GFtAjFNs6EBHEss2PGRj8FCQ31qw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T20:37:53Z"
    mac: ENC[AES256_GCM,data:ZcEqLUyVkCbhH3re/7VtCuL8xQD5WtCunHj1UdcRBEcJGsnOqIaEVV81shOj83QVO15Wxs7M9Yz5C4cSKWY69nJes2c6d795lwJ/DH9vwdP1vUTWxaRrKnvMlTvQm9bSF80t2xMBedItJQZXdk56aOe7BA4EW4wpPTO8uGAGySk=,iv:FKqHUumKoRgGzNWICrn0/KYcYkbalKHjeUDonb7a6nU=,tag:UD840hpa/f0741pyVgCFzA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
