apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:J808Itn9VGdjVFnbeIdGRWZP5TSwsdw7r58eVIi7fMKnZx5bXaGm8cxrWi9PpKMZE6d2xcrA/MSMsjLJT47HH+z7owSZr6iBwpwwsqcNqZHo4tInnR/ZwiaSG9RD2lyIkLtKAJP2jqpEWFuzW3aaRP0TKYelFRStIiJGu/qqLuzmgValabQZ3IED6leVpGl1FYZYMuMVWNFpfSPP2Ttk1rHrxg7g4MkNVLyqeyIWkxtrnFi8GLJrS1gtv7Al0CNzPCCEgbyXd0zSlhqJ8TMEGgYTvz0gkhP89K/KXLPVqMPP9mFQsfP5USnUj3XvWvAGDvcZGU/xbBhDj6YJ7zl0vqyNSg962UjJch1bNrts2MBAGAhaneUsk9g7Odupj60N,iv:9eYARYfLrYAsREEocOERFfQDef5uAj322V4eXocGPqM=,tag:YSf49WiBJgeNTiBtLh6z0A==,type:str]
    identity.pub: ENC[AES256_GCM,data:TCc3ENhbc93fnroUPNTQAsrmebxrMe3cwB4i1Iox02xEwSbuktGHkTYkYoy/Qr9W+iR+XGNiz8MvUF5b3Q6F0YAS8+eNY+uvefPP8Wz+PIstcqv7aO3GdZ6dSXLwtir2I5lbfF/gpYbdtFt2F9ZNWi6p2C5A05vzvY0/ZwMJBW+Cc7wXu7di7C/nG7rDv7N24M9dMVp24wQL+ol2uCAMY6bsdp+YrsNZXDFa38M45YJpjXL9s2x9C0ML782ev0ehp8EYg1Ur3xHplRG9Mw==,iv:94DmeBEcXvG40gJLHt2ohBHT3BbAvzw+CK9+rZ0IgOA=,tag:ILs8pUUDTzNrX9ijO3zSGg==,type:str]
    known_hosts: ENC[AES256_GCM,data:jHI3JfF8eMTg7n0TqQ1157WOwQNBxMgK02FjBwUC2d0nLMBltpul/8T9VkpIeX0e+Z5uS64uVp07Bd9s+s+uM2h55Y0vsmB5y0bAdo3u5kJqKIOueigG/SfqbAFbs8NYZ/N3Y5f40ayPwpTXDWy8hsM2TjAxhz1E7UthSVcVyd6GiTFRgeHAdWDqQ3tILheMzdVv+IVbsKi0+tAX4vyfBgw8B1HrWcLV4c88,iv:GHOTEIWgJoZsYZ6K8hLfmBSbE5wewOWDkv1OkYCSBIk=,tag:IGWzDPc0VZlVptn34EbK6w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIYkZ4L0RESnBpUHBBTXUz
            dnFyb1I2ZndtR2ZxdHJBcCtjWmsvMWduKzBnCjdWT01KekdkOVdObHdrTEUrQkhE
            dEVwOTVzRTRDUE1PM0ZKQXRGQzZwWFEKLS0tIHVDeFdPekExRUtnQ2tZOFR6RUdr
            a1pHUE05MFI1dm9nSHE3LzJvTDhhRm8KFVRf2aChrnuO3VZWpxv80QZ1mSW4R2G3
            EU0/dKDGCYQUwUMuXy8mw2XeZF6VSmsg1KhGFdEDVz/LPtWIByibPg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T15:16:22Z"
    mac: ENC[AES256_GCM,data:Px1keQm1kRlUTFOig7xwagtrwwi+b/M+givN9onDhRPNvkNzuy2bmkWYy3Lu9TR6In7xjBkBpDtZ8dgq5bDf5sXRAcH0ybXsJZEP95hcn4pfthlthpUqxQFWDASSxM4S/zpjH96sMXgA9NYn/Qobwuhihfsvk4ZK3mH2XLvZYi4=,iv:53cnswDvBLi5I7G055Qe35vqfIhJWrRI/PZPQYbce8U=,tag:d141BQFZPSb7Sw1f7MjYZA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
