apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aGCuUCq3wwqH3u/hpR24ESC9fNwLXQSNoXRflYtWgGm5HAYfhPiyi0qv13Pvezup7u8cLJs9s2z9AHs0z2r63GNyl9QUP8OeZ6Ed5U4g5NwCCe9osE/E6nQtC3Jk0k1DRIoy6xMHh2WxeUKYqAvr1UvyHhjB25VtOdlFGKDYsTd//4jqd3cDXzHh4NgNQz9ChxaTnBsSLRlbF9z61JX3LT+5ahub4mc97+0P0UqCJOYaC9WeUmyh7OHMZAroEsncb9T25DHMVgqKsPg7N7DRFEPI/1Mbue2PoWezCPqSNkoG/qyJMGs8KmPi4Zi3L8+Jsw3v7Tois1MnFNAUgsk8P6alMUfvv8gC3WfZrCCmpBLPJ9rPQdU489Lswi7hZwTl,iv:AtKLhcg3JZSWeIlw4eSSg5w0Aj56ujGjHXHGathoSoQ=,tag:Qh4xQXwsQ2mnhmVjGMn0Qg==,type:str]
    identity.pub: ENC[AES256_GCM,data:+ULIEiVlz00QnbWg4M9P1gFtB4b5DR6ZmuCSSzesxd9oP6+IpaUB9XT97dvS37BbilGol4yZwLmEiFhWbxNiqrXSzlYtSTJDFXe1dXsT5I1KtgVG6vUeb/0AK+fPMXKGTRVJJeF2oMwXcZH8bIAGbZ9xxBPJLwTbvGemURCfegl4jYLASSToM9iY2fd43km2wbdBrMB9ibkq9UUrjn9Xjt94US7luEM6ecEAvuWAELJ2sm5ffon/GexaP//W4dUiFKpovfY+phKQZiDdCg==,iv:BQERD4i+kOziRAh3BgoH10lyMVh10tagm0ixANlIfss=,tag:JFk1BVJpJR61VwyKF5I7Fg==,type:str]
    known_hosts: ENC[AES256_GCM,data:LCHmkmhy2b9oSycFZQN4VPI04W+rhkb9BSfZWIpJiZzVBX91+B92gjRUIRn1eTNitmVTwVINVqmPR0qGEv2ZwzchBf8udjMnDVruGqwpA174AeYCfFVUeJdIFSjEVXjf1j7wDx+H2ZyiRw5JDbMW0mqWppsTMfRyYcnx4NFoqFOHJ6fOPiSwioqNP3o+9jEdodYaW7qKyCEPTwRx1uiRqjkOamSdU87WsrAh,iv:/osb6BXpXmsDKVG0ascJenpyvKdJWZLi5eXNPQooeMk=,tag:gtMpk3S9alvQSQU/uHjJuA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMnhOUkN5aFZSRGlwQjBx
            eGR3WXRWbFEyVjZ5bFcyZFd0QVBaWjFHWldrClJOM2EzVndYNzIrdm9wZlVWaEU5
            NmZZOC9hZSsvUlFFd2xML3k5N2N5TE0KLS0tIGQ3UGh6c3hSNXlOcHRtUDJYL3pl
            M0Y1dE9jS3M0K3RJM2xuU25wSzBuVlEK5ly+i8aVUVtc/+iceawvHMJXDl+Z8gYa
            LoTmWV1ohR3T7y0swZ5Q8Fx6tS/R64kw8MQdYi/mq3IzlmZKrneu4A==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T19:57:25Z"
    mac: ENC[AES256_GCM,data:6yqi+ifunc2/7yQia7u+XfuCYucxr30H7Q4p/AzNGuGtr9ggHint3WEAraZH3HLi4ePDv9YL4UvxrtaOTNb6Nw1ghI3xBlBsmPGlnoBJoXGAEUChbTrBnbgiFp43EfCDCH2nMmJ3bl5r2zUMsFGAiLHWAd9pRwAcVL7Nu3UAEpg=,iv:cty88NsTiO258XkRvT7WL9BaV5DVB3qwI2MYLIOeQpk=,tag:Uk+Y7l9L3Dn+K3w1sl+EGA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
