apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7z55VrPHO6UmuWn5q5et4RlkILoUbRnCN7JzzuH3Yy1+UPyYZ3cKi+6yIDrgeHh9+pOrvYxaxusvdPQXciU51nMGtwi52zgrrttVE0IUtGWoduN/oKlmYXa9pzG5j33Hnx33n4dJEQYyNz+lF4rN3jS/RcMddIvhh+C3srWpR5XNXvy4xkW/a4KyMl3qtWfhzeLquez1Z0Trn/v67s4rQUnrbpWboVB116BUhAP59cC0Ulz/DpbIsT5FXS5g/Lf6Potj/652/jbu4dSJ/yVI5lOfinJaoGGGEk95lfg1ps60SloZbVzp8/UQ6ZskFyUu/vPQa8WyfvmB9LcY/TdUYe9vu28rhGa69ITECjy3J6CU2SHm46KRW7Bjhzeulu/K,iv:tFOlQYFaIYMI/O0inLtTwVdF4ftHK5hs0kVHK81gfu4=,tag:QXDZMCMbBIKqgp6qCSDWIQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:UZPhUpL8sDVyAIQKisdTVlnv3P55m0W730nHPVhHx1tS3chtCPpbJWXgFJnGZPBUOGr0wHMo8yJ5wscjroxunH1s0T46EqYczfOMlrodGmWiV/GeJshL045+LAE0CrHVwlMNHNK+huzlbV9Ls7ZCRFn/fRcPeSB9Q5w/hklOl7h2S5IvLI0OA7pwv9424dgLa5kDHFmATq78bYj4zwdDYp5FST1PTWX+8jT1q1WtXn1UCxjMx2VfyIb05s+C9HSO3C2s2k/Nk4AoD+PPJQ==,iv:dGVd6zWVz5IXqs+jWRLgtUVO2NbSRhbMf9C/H5zrMhs=,tag:/ghnfAFBg/6d3ZZHKwyppQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:Y79dlSGUlZGG0NlncWGt+q1+mwLp7f+Nuakq6/0lNjy5y2UzQLSsclCtE4u7NNCqdXkOYsq0+AVFXZ6/TcWyZ+sihZ6BwqYB3rIahvrmf+vupiVYEan26AsG82QnYBR701J+AQzs7PVMLAzfiLVP+KzHQxH0WTQeMdJQr0Uhu3A+iUbtbcH3W3X2nbMEBEpVodZ0ouqXVMWhBaBjlWPOxJByX31/UqBAor3z,iv:Qq/UfoybuUAq+x30Nl5XMp9brkuC21L/qYxB+kJV9Ww=,tag:MCDzBlGKduxJGNTRDnykew==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3UFJFRFlxTDRHRWRTUEJz
            Umw5SDJ2VTJuczZHMUEyR2FYQVpRa3VQdDNrCk1mUzZibHZ0c0phbk9kdXFES1F5
            b2JrSGxMWDJ6cVV3QnRBTVdKb1BrUHcKLS0tIGszOWFLSERnR2tORUVhVzlEK3I1
            eWZuOE83SjE2ejRuRmFQSVNhL3FQWjgKiBltm4lWbBqfgaxGrQfvmvxFcy99qfJR
            xtJQlnKQHj9W5AfD/vWlFF1SlqGfNlP9q0MWAeihH0sGGUZZ2Qg4Eg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T15:32:16Z"
    mac: ENC[AES256_GCM,data:kXiSZqpXuRGvDrbDQk9FAiESj20PS8BN8vWqaHgbf52vPgJczcuk9UeyeoUI4aJVZxN1ev2m+aXYpgD6ss1uh+MSSrzltZALmfnkNrqT99frLnvyDnVBwy0XynBfX8LaKn5KBalW7MeEJYHe3KTuggD21TkKJzlt50jL8wXgRU4=,iv:TyPVKLPVQC75N6dxuqa11xSZ+EywGc986CzH6eIsKmQ=,tag:iq/nXx7vEUeEPSZ0L7IIdg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
