apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:xk1Xgy8kIb+1IgYuSKCU3dk7l/qPva5uCXyfwnUZ21HQs+GwXMJxoey9/iEK3EnCXnWEkQz+3/eyPVZ7pmdIVLTfDIC3eCMUDAsudGQJNjzrks1Inv5DKrR1BwybfpK1frTkmcBmRB4E8HF9Af2Xy9tRdBKQNo0HkIT/7HF5od4P/TCaqKono8j4KDVrwr+V6TEXeVnLy491gqqmbAHF92OUE/j004Eu18TNjfESTMzHCOZYguoEdIm0cNkZQ9QT926SNzC/hdnxpVqriVHMpPIT3FaUZB1aGkVU3rk+OO02GnQjBjjJQb55MzrsxSAKfkmacLuU06QcXtm4BzHW9Ev7HTXthBE91IpXHqBrKiut9arqeSNIfK+ko6gi9L48,iv:/mhxIQMb0HuMZm9NdV4CBYWYWePENAjfTy2j8X4mBK0=,tag:7FuDLLifgVotJXVzI9Xj2Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:8Ar1/chr8d3zRVSvmPwm3vssLRaK3EfsscXRRHujZp3X38/i23Za7cdSdRRSj0YpH+P1NyqfFw2TBx7yIHMbV6an67599dvtgOMex1Gto9Ge7YImCQ8Flz4saM8uNlb6vnbK9rwPabcqjN2p6HwNrlVeLJiBJTLTZWQV+QPbVDOBSqGPtxWWnqeu68FF4WZaOmfCLXVI5xxE7KXQ4dUOalHPgZlTAMNsL8P47QZt4B0WRCfD7sJGXEaszH0Z/q9m1hg1/yqSSmLVMfJG3w==,iv:810jRMG5sTFhjTLCQd9s7sWpTFFGE8inTsEGyApK3q4=,tag:jwSetggPe+X8iWHs0J2e1A==,type:str]
    known_hosts: ENC[AES256_GCM,data:VUY7YgXlG/zoRfapl89zD7xpSTHXIdrdNR5ZjOVfMNpINRg53h7SL2FWJrznAcHDH9T3/M4CyhlZRH9yx3latMze4rcyiJw+4OHIJaQLl2MgXG6DlVKnJp6q+sEbaxnE25k/ZzEnizlyhmT6NN4NFdjJo7fPef62XwGMITNitrDO8GF/ttqW68u/1m0P1QRemv9t75HrYRdxHCV7bH5Jhr3lRy0uKFgc7kTK,iv:44G7hN5KUhrxN5xkD1q73CEc15jyNUT4g1MsMogjkD8=,tag:wEmFA47eOfzu0cYdIMjm+w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB1WkJ1eDV5TVhLVlNqbDE0
            MnREbk5vTExnc2FWNDNjaWlDOVhCYTdpa1RzCnA5bTVrL2wzSnFmOHl6Y3ltd2p2
            Z2hFKzRQWGhOYm1lR05qQ3c1RU1LR3MKLS0tIG44L3V5UzdJTUNhNFBjbDRPWEw1
            ZjJiVmM1MCthNHZ2KzBxQjhNdVZLbGsKqq1RGcHzpbhGJJZUoME9RjkzwNSnG/yw
            +6DQFyqLadF9CfcKBXpGkEENXQE0clpkFHuzOXOCEGRF20aOvBI9Rg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:43:42Z"
    mac: ENC[AES256_GCM,data:8MGpovsGK4eqFhFlv3OUq3j5Xgd6lmG6U3B2YHilwk/TgeqlsqnjZE7wqr9EN/Sa4EyZYZyIq9aQ2MQYRcTcb2Q1iehwdDX7XG/QWxORxGyhqLXmPv+0Sv/kFughPj0rGas1Cc14WUvQ4gU3LuT+tP4X6IeXco/3RseoU6nYQtE=,iv:ZYXLienbbjn0vPnVg/qlrRpn5s620VEUhsuESaGfl3s=,tag:35Y9F5eJy2/kjoeHDdbHRw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
