apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4dzr4Ks7/XLPDoNEUaE/qEhNbC3uxEMFl5aEvd7Xsdo/6hPfNDfAS2fIMymY+MkxzA2vxPEN2BvFVF95Uj4ymr1B0PoKhYEVsRxqmxZk45KoJbl2nqZDTYv7yRgtsc6P5USXokhHxqxqw4awKmSWQp1ardGBk0UcSRBv0chymkGmsUpy3WxKS9CI6tje/j3Tbgdc4j3IoflVAKb4s8nvH05szz93YuARb2U3040yXdV1aJADd4K1rPX99sUYJPbH/YwLRZ5teYTaYZQwpzOLgo67R94VW3pc6rr2EY2sVvQATUlCUpHqMuFHevTq146UPwnGqwHBQlaFkpgn+/nKb/kAeOZyJT1G8QDOTfQBwu/vnWx0n/37N79zz5NlLp5a,iv:kHcOLGHRjI32VIvgu5eFpZJcH84aOBZ9iyaIUezmI7g=,tag:XqhwD8e3KtdiQkz7a8BMpw==,type:str]
    identity.pub: ENC[AES256_GCM,data:yAZLu5tPWE1wr6Sy+I1c/beo7gSu6DgOpUponLpDlM7cMCHlTJB0506Vwsibtt44/ElHJ7qGcSrKAyx03NdQfBmtvSGKgUI/J0IPBVBUTomQUbNn3D8R54CO/qQH0J2o7/6L6n8HvrezOt3Lbjnp5JXPIgk9OQzynfEZQHWUVpSTzUntLcf5GmsiBa9oHDSOPAOa+2+j0D+W/e5wEqfzE6Fuwl9rw94mcy4dJTk0G6NlfkwsQsZEictMNrDQ110DRY0MqEoCoGma6eA6RQ==,iv:FW97d/BDyxswDkjRMtNqXpKw2+iMhnT2fw00MgrlKPc=,tag:6KLppwt3adgFT+I5Lt0P/A==,type:str]
    known_hosts: ENC[AES256_GCM,data:Jc+QTwln9K9llSCu+LSPCVsgiCkWpvuOnaOmv5Ho/EOgGXQOsgAZIeh7ge9AIUpWV8DTXR+21WKtXq/Z2/NOaR64ek2MYYTKp8EBtKryVlFPfcqWUdGFdmGwdMi9VUdbYBu7cXzbj6pI/Lfu4E8lBBdiQYbF1Bu7XeEHsBSYhxqBRvLtoX9jr7QeNKqOdbk9NzFN1rISs3657GbcF9cgPHc79Sd0KphCtgc6,iv:Atsaez3rgOenZs2DS8TWXpdFkKh60xp1g1DvUyzhyWA=,tag:vbtPrPkF4a8omcvGGk9TyQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpbCtwSE10Q3hkZ3pCenpC
            OE5ldGg1Y2VITXEya000TmVmSkE3VHdxSmtRCmQ5WXRzSnVNOVNyZUJ2YlZyOVBU
            a2xla2NYY2Y0VHpTRXFBbUtxcVhsRHMKLS0tIEg4R3dxVGJIaGhNbEsrdW5hR2l5
            K3d4bnNJa0U2aGNmbTlrdk5QRkdtUzQKef5KtDA/fXyfSExMvOcO4Qx/4u9vvHk3
            EocRO/aLP0S4QmkTmUXIODCwClXiIt6v7WQ3ki5UQnRVI6XQrQGeOg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T17:58:00Z"
    mac: ENC[AES256_GCM,data:H9USZOQw9a82Ei25L87ofkgDGXetQHkSvJzyd3j/1R9fxw7194aKGm7B0M3vrE9MBr79dTkELge9i4Hu113E6H2c2dohtJfTwD7t7NAz91Y7DwcY2XJzhbeqMXr4Vam/Y0/Cr5KQIGwcczkjD+AA+ILeV0seSZSDROe16bm9l4g=,iv:vaQ1J7heQ+hYj6vrXgABY6EnTz/Q23810tbIl0Y9fJI=,tag:BJWK0MKfr51mEiiKLsLA4Q==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
