apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:tGEyE0TSQIm4facYrlcRK9LhSkuVB12eZopPgp2q3v0m9NXfx51DSAyljhV+fjnhgkpDT6aR6mx7xNxBgNXhuTBYrijb8w511LI7rnupvxPQu+axVrMn9xnMmueN4uzyLH7spg4DtCqhOhlPa8R32Jq0FCFkz/k9mcASc0wANGEggo+B4l7VOIIlw6X6/SYkLl53xfha8RsONO4jva7r0v43jXXKumApBbWFgOBTVEAZ0dV/FK31T82fxbDi19766HdGZ1i87rFHCkZDvHaNQF33VfxZyOhCVXA7SEv0/zsqRX4TOVN6DQk1b1sA8nbSxM8Dg0Azl7E12lVyjqO0s5t6wn7XfUIXHN6PWdlTlsChvHjgkfXZqUhmT1G1+t0F,iv:TcMkuCyIigU70TE367dFZVr07tixIZE+ZAITZ0U0L5E=,tag:14hqOFqukt12NaAm9TLu2A==,type:str]
    identity.pub: ENC[AES256_GCM,data:h3mgD3e8E0cRBhEYZLMvrhPiPJoF6S9vyCXgjUJ3zoR0EQIFgsklKp1xH1S1vZuWSMYKCRYiwYI+GIwG6jupBL+ZuFMkhfkz4wYS4i0BIsBoSsud0zb2v0aGAQEZ4jvYjdR8crJsgKHPf8DjMgEgs/nG6wISRRhnchJ8zXPTvgfP1R6n38OIh1cYffetCQ0KP9HVUbVFWDt1RMbM6KrLJ9mwHFdt+CVHIopPmE57zV0guW/fPqX6cSS26w6FGCAb411FaAJEYvMGFevJWg==,iv:q5SuUPEpifAgkeZ2aRp/AI9ohpq0r1yihSCMfSsw2oo=,tag:mrrsQhPkvipWT1mEp32zDA==,type:str]
    known_hosts: ENC[AES256_GCM,data:kDB27FkV+tg14XDem+6ltq5+pIgXu0XW/jeeTbhM3TKis3IocmzpsUe2OcCy/FP90Yv+U59RVESluizQZhrZPqXCnoSyYweb66mGBHazYN3UELUZJ1Xcf6u1cJ7iEVJRTDvJ5Xh7Cp6sJn3Wf/SeMXRm3+XCNvGqTljQktqH9Zsx4GRoCXnxTiNpZsWayN2y+Oi9zjlEHE9emurHyh9LArsZPs/A7oczrzUP,iv:XAPI8pNVYBZBgOf9+DbP6PFu/moLTuA//d+FkuOhiH0=,tag:UrzhV4/ePJKQf0NHKqMvCA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBaMUxueEg1ekh3WHh2bDFK
            TENBaU1iNjdHSmFWbDF1V1BkRlk1c1ZPTVFFCkZvcU96YytoM21GMWJoNXJXL0ZH
            Z3lsczE1Y3N5dUpxRmpieE1UeDVPUVUKLS0tIDdHS3FYZDNtbVZleWZvdXIzQ1Fn
            YjdldFUxMmN4OUZobEpPYlF2RU5CcEEKs83YD94FgAcc2UqwBx1qjW2k96KeHGr0
            b1pvRSj3YkdUy1veKCSVErj6ZkmAbYHX2q3zzw9u3kFSjny+yCCp4Q==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T19:58:37Z"
    mac: ENC[AES256_GCM,data:rGtHgnemDmwqtak3Lw9Z6dXK40DkHA3AK9rgqpdh7QdMDMRNOpx9chCTKZfaIkhTLmwz7PqZd5FwjccWlpj0TIANeQn7IclSbxxffZX3SRKXqTHhNr2lGtRShneqrU30O2R29sVs+bBM+Ur2E3+sEakKEibjlWAxdAonevbK8yk=,iv:P4NuCb93OaPXiul1Q4jHsx6h1xdVOqYARmtf4Wbtqk8=,tag:/X6PTwqwndJcXj8fMxrilQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
