apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:3VFY185zA1BfWRi8wtrQqNZ7hpLeC1avRJT/gxlnAyj4wdup4F+aOa+18CY/iWkE2Lpjzv2NBUiHMZkP22hxJXgI7a8/iaA/myykG8r8K1IKMjzFfRZIBDkjcSWd2PeE95lQfz3Znl9VqykdDIeA7Fyo6LdT17YieA8SQbuwn9dmaNzduE+gEb2odaXy5JY0pQEJGo950dIoh7XfP8mL9NR2CDkqtQvnWdl8+L0ThrzL6qP/QsqCQE8Au6GiQOqF9sOSRkX8+jZM2vfJlbes5XiC4Mwk7YqWEJQE+UDxYTY9Vau4+VmfgXQNieoBdRI/g3T8DwTJC7W4oMvNHTuGGtdi/JN/vYx2u/G2YGReR3KFcIcpOa6QuBHY++gAG+nx,iv:wStGRkaK8cqx5+NUcfbvlfrCzvDlgBE6Ytpf7yQFsn4=,tag:tFMyLKWxec2CW0YTCjNIGQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:tu+KQqb8iWFL8OxQJvcYbPaFICpfcdbKXKO2AlQuTRqX1QtIAoLV6bjYfLyrdss7qDSvAinTosDrYjYFoC9KRohF3DDdLW1J1Hue0kQ62zcow+foNQeNoI74jyxIzrBJaH1fsfkFyV2Nzi9XU2rv93QsnqBonvB8WPg0fft36+x3PmlCmbZh9q7AbC8oa0uJUoUgFUz0V2tWbW5LBKSCHjTDb48D4Z2K50M7UxfBc1LAOX4XKVggJnXzTn2PStpcIY4xSFN004JOr9N+WA==,iv:dyllQTxIsCdYvK/EGDIJBDPcbJ5M37qbSa+Roi4qqUI=,tag:kEecv7Q7Ep8S+XoY7gZ7uQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:RdklHgOIDZZbS8wJdy3ky92Xx3cCl1K0ScMy52ey1pC71vdY0xwHf+JbNXseIqRmrvzgYczbwOhUKSWjngmfzs7cT4UKW5Y+8tj2hzM2pjrrxEyuWxVKl2gSpnUu08jpy1DhE3KljzSwFbnjxljHsXLt5UcugQCsbSRch9apxWdw2uwXnSzoqGGo9Pa5RNBF8LLuO0rF4upjundqmomdWNth9hfyk16ffGqb,iv:EggL35coL6xxEMNzvk64zfP+nF0dpCfqaS+p7Ine128=,tag:/dMvEnH8r2/0tnDCbLzDfw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBCZC9jWFRJWmFkZG16Vkkv
            QjRWaS8wdWRONjI1VnN3aEhJd1g1aWQwUVE4CmRDZXJIaHhpeDBKUmV4UEtMemgw
            Qk5FalU3Q0hYZC83WGNpUFFieEhiTXMKLS0tIFFxcnpxZDdERFdlT3I1MTJNdHZK
            L0FRZmQ3NitwM1lIRk9rNnpXK3hBQzAKN9S5J4DurgHuU1SCO+ADucK6W6D8w79S
            P+ni5p1eDtTunjDdDiwjYsVtnA0jz8/0nIv0gO4Aquf+DZDuJCXgvA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-27T20:35:31Z"
    mac: ENC[AES256_GCM,data:UIsZlFud1jihCg2+e5ALnpmIUiRrWMX2XfCz3ecI+MLNWfJjT5qDcyffSsyhp9OrNzvSP7hTPDXR4uCTXzZ66bDWVwfZkUuDD25qp62BmW1kEnydj+aZFSOkoag6wf64RiFAk27otNg/JtVNe51TG/IDx9RBWZm9opyb4SSGzb8=,iv:w3QFQdeh0bn+AhHRXYyF30ScI+fDoSdwdJAxkXdSqhU=,tag:q5TYTmkAO/ZzbZHFuGwADw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
