apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:aoOkHKWb8tp9DmclHl9VxnipD3IFnva3bvcnllEJTh4AWIYbW0evv04QV0N6gQ9R69uowOOsYxt29TEnexeq0fd7Idm2tkT1ENbF4LnaPiKbgjga9e4A37MapK6GZtRBKe0OvGIsUtcM3HH7UQ8I3k2cwyY6KPNc6sBUuIujMx9yLdSI6tKqSGA2hIRZ0hwfq1IncCp1chDtbe9vqt+oRMg3Y9fpKKCa9YcM73vdcmyeLJ9SZRqCVUjrTr/pDw1w2+jK1DoYJgYXmtWWXN97uUi9MnFPSRc8pRSudQdIGKN9xAdQTJ9Ipz9Rtq8ISpm5Ib+pxvHJ1jq8VIYFjHIncKa4m7+0jUFGeRgcN0x0cBS6uRERH5APYTLWOdtqWM/u,iv:ZDQe5Q96WB0cDcRDAGj3FJVJ0aPEBvSzCnYg5cZQApw=,tag:MpdlmFBBpKreCxz25owktw==,type:str]
    identity.pub: ENC[AES256_GCM,data:2wWaNP5ZTF9xzdwlIP/s3lLFS2KkVErOnJMZo7xDqpaGXdc4MtCcPV3P7vnwlwFnTcovzekIwuxQRJwWXSilj+HaZKwepcDAnKHeRsG+PViu7v2UMpPlFpN9mPyawUphZxNF/T2aH/5tArfHHqmGDbXuWjdlzSsNkXxX5b1Yophqdwuf4v8kSY1jplBGkq0xx+qzvXiFQaVorBgwEEdx16GxyYO1WV+bse8cOG8oyYDBK0YK6G9poMjk7DTHIUJ4RjsBXf9Mc7Ikt3J5fw==,iv:P2sJqIARUxa56BkrkNGKx8SQuKTapi3qRVwtlRxbmkE=,tag:yvUQWwnHiyjhW6UOMWyvlQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:+e0KzPbWkPudEKdueQGsWjONkcaU7yvanQjs/Lx7XqRQuO2Fg2R9GrhVYTXpjBbTSIDRFEI9dTZjVBevuovi4RWwXejGzyrK9MoY5mUSZQEagVceQwYjSozcGfBMkb2gp8ou+SLeAJbk/oCwJvek8Jj7zc4gy0mafYfVXZb2ZaDuYnIZWPyL6g8hrjJlCN92duHLDI9aKiB4b1UPRgXo4OJpO89ijrKLvdmB,iv:OisBSd8mbGAI1ZcESDtibJW2ePQuHpleCFmur2t5uBo=,tag:2IPePGhovwPIoiPk9pc/4g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBNa09nRGMrK2l3cVlQanJZ
            VHdhcFdCU1FZNkhwT1pkSlk1TVRXUkFDTWxjCjlaYllTbkRVcFNxZVc0SkdWNitH
            SFYyTnFwV2RiWldXa1B5NHdXaHl4aTQKLS0tIG9TZzhKNnVtY290MVV1eGRmTlZ2
            NGo5ZXhLSUVFNk9lNE9SaFQxOFVMZ1EKXI6YnV2e2BLw07FRHnCtX6oFzPWd5RM2
            fjPjJNSBlYa0a5yLPciAY7C6h5wLA+A27l6rtXZjgVxp6akbHr7TLA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T15:30:06Z"
    mac: ENC[AES256_GCM,data:FjJnMhCytJTIKh26EWiv1XYQQFRyVdw7ydPj2IUqj4DyYAiIouR8pdY/0qH+TJNpLqIAzGvus7Z5SNlencUgbLPxHggzsrPOKvp0qkuKMnBU4wHs/AF3D9QtFtpvjnFh1kUbzdd0IY5wXaAFZ5nBzkhjS7nqMrQesPtEUKHCay8=,iv:hnbefKebbHr5027wjJFwh6BRw+vQByr29Fj6ryTJf9s=,tag:zU3BM2OT3gIam1AiSTwvGA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
