apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:jyNY1/uwrQgS5qKDu+A5xoYEKkr+wroC8HZId2R/LuloP/JfqxxhJEkXVVx9VVXrbfKEK6lNaYxzwqD8Ysj324PsDMUyKoO/dwJe/MQNm1JYyBhVPTPpUMkUmK1P6vWFcAWkqKYS44knjL4zHHVs9CVaGkgs6ubmoy8bHbWQib8dsjGo3OJ1eeGX+Lq1A8RgvFtZfaRK7da9UC6KiKs08RZdnxK7Tdvo3RFCDHwq/LWpJzGcZsnPQ7ZDJVsXvP0+8D/WGRNsudvFNn4ZunWDlGX20DfHIGvdGh8G4hFmIhYVffPAqw8x9JUfyrDUs2+s267XBtpRuQwuQddcJrNlE/X4drF3Umpn5Y6/nfWgW62YG3tYAMufr6hJXkWHrEKE,iv:w2vVyH6MwX+NFU3o2hkFfnhAHpSU88v6DrKdTznzDzk=,tag:i7v3mNpKHS/Co3ucRwkhzg==,type:str]
    identity.pub: ENC[AES256_GCM,data:zYUbHqwg09Nj4PljA5WrW/HE2TRI97HkHbi/9i5QfIbGvNYwtbCVcwozlwx9SxxfYhBiYOYq5IlqFWnWIwkcknDttrLcxezlj2W1ml3dPoeeCaPWD8GFLjX5Me9z3FH8dCU0FSTYrAeU/qNMRDeLF4+sJn4NweMtkKwv+HiZPMdAo78ZMZ7WvesrkS4o50l1FJKX4VG4lzcRAjnyhvrc7VIigZW/d5ynfO4BuIuMjc89IX7A6s43pK9eZUz6ZklxSHnYRq7IzmK4G5RbXA==,iv:592woKKJr3Dp9JJrE4jqisONAnfeHlTZcbGrt7sGYLM=,tag:C6BBNrmlypR3OhPUsRgJTA==,type:str]
    known_hosts: ENC[AES256_GCM,data:OB/HVQlgqqwoa8K75EfFn51cK4j6L9Fy9OWSiQV/VEf1l6R/eZyBUhu5k9cMEb7zFKtXSyI69HPRi22aiqHog5iI4q5TEH5Acpx8wFsBL9iJpKv/y8vi2ubPGgO/fMlwJJf0rwBrWKZtLOLJGLFzcZiX2fpEHXgMe01drFawLC0J8Nrgo7TjIWqZRcw/hBR8SCHnzktW5GRIi5Poy3CF4JQzLw0A1Mnu/ljm,iv:Fal7YNkUE1N9L+kDh3CbDhVFMTGpUAotEsOXFvVT/xc=,tag:3KwNpturzd6a7xyG7Nd33Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBJdWJCbExlZzQ0WjFhZHRh
            aUVzNHZMMGJ2VExjNXZ0cTR5blJiU0I5aG5zCndHSkpJeGlEVi9NUHV5bm93Z2dI
            WnE5ektkcTluQjVEWGZYUUk0NjN3cU0KLS0tIFVaK3llNVhJZ3Z0aGtjdkRDRXJK
            Z0N2U1h3QTZpZktzSjUxRTQyd2ZiamcKcD76uGYj1OSQKwQ/QLj7XqdZlr9ln4yz
            exxdEMtEE93SQmRL8xsE9w5qNd5xrGq+LdWVOYcg+HBFyOTl6ioQOw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T15:39:18Z"
    mac: ENC[AES256_GCM,data:QDw+7ZQyJpQa/ljdxTiMnqzM58APB5nJU1hRnUDcJSYHNMUwat7A7XZr9Q1u6ezphfo/yibm28kX9AHxbElKALVocKG8XV0LvCGj4LmxrE0t0auxyocJ96OJPqgdFkl11MzVoDICW/g8BtcEHNqJPTKFoqSZCgkqYJbssPnMvpg=,iv:gy9Hg62GGB/Cs+oMBIG2s/UVdS4igygaq7+qJrFVPN4=,tag:1xjUeCeGCmB8PuOK4cZjug==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
