apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:5L1SRxxRyYek+hQdq/W5rRzmjiick47T6U2PjvE4M+fQY3++JApQW+4goZPIC6FEvp8/USeNKhLtVfL7VAUahyzCLVYtG747kiyaoTne7LXYDwsEK4ddjFleHnge1S4ZndOkUBpRlOoOonfu5UYoufFOxa3NUY2mkYdf8Xi8PfCk3yhjNwcH8WevoWWYqQpIhkXX3jC9bbt4bBuOwI/NkEBBCn6OX7GALZNjV0wWHxK+Xuzj/lMRA85bYzA6WnMIOnGWiPADRe7MGMd6oBeSgVnT8JvvztoF2QnLzsELxFnyOxRn3xBrqW4MHupS9c0z+EWMxmWlwdtUHpn2bmq5IOTca3mglTnxDPZYPQUtlBxgq8oGRbV1eFDBZ6zcSwDz,iv:s5gMcvyc9zUyE8fwplSON0poKcB1DseSwlFj1jxLC5g=,tag:AncpJOlR7HeUCdNCcU/A4Q==,type:str]
    identity.pub: ENC[AES256_GCM,data:IzzU39oYp+asL8DZsGIOGTKAlAKdoUIjf6Dgz8g3+DXDKFKEhDXBD9oyKVVjsGKRyrRQmN6K2l5mAv120clwPlfI4snR4InCZNOMrRiaOAHy2xPIEIgrLR/VUNDwejgoeO0WIUG++wF9PynCGsRH5EA/7gPTtSt3Ei5DFalF5TlRW9DxeLZlP2ZOlqXLb/PdmjJdK01dp02fDM6bKF5LBc8v/yW7sF5o0zglT10VLP/Oejac1lNfETCrWH46QS1tK5RcEKfsRWG6Ysw9Kw==,iv:HAo/S8wLn10m7O0RRTqxaRE7JmRXFOFjBhyq2MNMCZo=,tag:wVZUvyIKuBHZAAh+K7pFwA==,type:str]
    known_hosts: ENC[AES256_GCM,data:c+1O8oKU3/2WDr/1VbcJvByqBDPRB6jfQQLDBR5eCabB4dgjXrPCJPZxHpvRsUmXimERZM7w5F3G33Kz2gRqOfqbKdgvdItOlEpBFmBP5xJT8zi/kx6a0vHg+lWj3xRjyLY9Gq3PSfDGD/DWI/39TixrjVUn8KnwOI3fOv7u45UsubcDX2ReOGtLV5/IIW/Kls3R8cy0tkFod1zTrc0g7yC6JVyTu0v6Kf8w,iv:EaaHEnng8amFNdAl3aLLe8R/DbzzopDW87CqD8XrLhI=,tag:C/eybYKZGSSABaQyLza+RQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZ001RjhhRFlObldrUnkv
            aFRDQkQvMmNXQm5Ob0NabDAxTWJvdjdRa3d3CjJPR3l6SmsxNzJ2Znc1Q0dvNmVT
            WWJXdFAyb2dxcUkrOHFHL0ppVjJyR3MKLS0tIEtmbVgzeUdyeUN2cWlKZndMMWxO
            b3JON3Npem9nai8rTXg0RTR5YnI1NzQK5DOWT4LQPfombFucH2T3ldMNvofprSxk
            5M6ZuazE7FbM5r0R1k1olnt+iWaL86tnstlAtXzW6wawEtHyDmA04g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T01:12:42Z"
    mac: ENC[AES256_GCM,data:abrs7xulTpXF5t+iaZvTUOQFRVVmyOVJObBVcwOeyUyvmkNHBVWwlyZlsd/BFB5mBq0rgOUAPkH74GmidxeDtwvKA82IHTRiUmFqAdxk7XGz3/2NlCbg0cjNb9tQyDpw9lhHygeD3cb8Htw1zNXyXMcnU4WAzxbYwPK7rkP63o4=,iv:+VGq7Ky0d176YtIVZpL9wRdRS7Ia/hRiru+Fh1LDdoI=,tag:wZ8jI9mJajsPqmohTQcCTA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
