apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:YnkGdsHDtOgQGhucrVYNwRHNPIyFITQoBWeuonE1P27Y7mrFTBcGUwvrkKiJWPqg0PJPahaH6tS8skh+kiRK1k0PQ07qrNLKOP7i3OFiJwJPSGcRtihZ0zrjApg/6oHFOpyX5tbYHgckTGzPpGI2kqTUIqqTbIgo7LMAAUxzO848+XVffk1DtWoiTCJ4igGcsj5LtPeShOOyXVKNjCJ2zaf4XFbue3ahYxlI6jhbKasuo9Y8Am637zRb3R0L1RhdNcz8JdDY6bJS786xe2SuwcYVnT65ade/n1j+xOWdtlHs3oqmHO5Zds8cxjpnZlrEi4Ql25jPx0bqfsuHz5mw/b4cfBcHmWudMykyIGdAt6P4HDjpR0KkNNZxoSCcRck3,iv:+1D7b4JKcqhqLDem7LJ+jLdaTEyk1+nI57EXtjFNfiw=,tag:FynjyJqsCROKtUajtVDnag==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZnFFR3VweKiTvovtpo/E7q3U6AIYJqLIvvuY7Qk5jTFx2Ak2K7H0GD6u6rw1kwqDUjtkPFItyXTdkIuKdMerp/UbiVWbm6bL5mC68kw66HC9v4o+0YEM31UbbSiZKePccbCFj2bCPVJH1nEQP1WvfW1KkpvPgak9OF1/WW9xIrJOdqJZwS/iM8Y3cWLO7dIC/p3WzXp+2iiBHyrqTGrIcPL1uQYM97DEOeQomOfg/QWQGOHWPbFiRw2aXHt4gz1jXLyXjjwADJpGR/P6wg==,iv:5d9keEGfri6uXpwXEeDs/ytdPfOqU/VSiRGtHN5zF9g=,tag:LXXV4HztJ8aMaqpPCdQ26w==,type:str]
    known_hosts: ENC[AES256_GCM,data:DXJTdhlXaM7GQ2xrKlymtlFUmC4HYIVgB8cBvEEucI70Vp7FnAaigj2BQLdjqfk++s8XeERccHUgFd/mBNDC76LRYZSOKuKeKqFwknIXqZCOB9eRDEhtqdA3a3Vb16MknZNpqQUTko37RQ/F3plVFPntLssqR9Rg48/jD58rTcx0kIJgyPSiNMW6XKoGBDgFqQ4InGR1tJCDFVfAcGERlI9/Nx9gSiSq2rCa,iv:BoCD/Ei25e0UL2VcnAy2ld1+NgqO15S4nD/vAVzAzwk=,tag:L/ox2CN9NoEcRoT+WFII6Q==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRYmZBOTRtYmdTYTcxbERQ
            TkFIZTRTZFB5ZWNqblRTUzJHU0VDMkhyR1NVClpVRm8xMjhiaVhxSG93d1lYeU81
            R3JPVVlGRVp6Y0NqRFpoK3h5MjM0MWcKLS0tIERnd0txazZsU0pXTDNQTmN1QlZj
            REZWOVpqMmtpeGJ5RkZpLzUrMjdDelEKHJXrg1qZVh7aoudigMdHEd616iI6j5xW
            7IzdyMatiqvdN7aVEVqszsVtaSziwoeoviwD1fJw+9SkowRZFsb6sQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:39:47Z"
    mac: ENC[AES256_GCM,data:FLh192/v3d0H94bs4VcHJv0sYs2bDxGyTmZctNj6Qc6C8UNVBpa6JbufHldMCohv7gNf+FPFArcaoeGyEqa+ArYCc4c2fHKJKo5MkXBqKmPNbRfkFKNlZpg3WaqOEB0aWas8eyTWJRDtuhOw8xr0vhaXUuGlNLUp8SxCcmsLS3Q=,iv:CI6KavZfJT3jCfJS6V/I4/xcHS5zhPmqsQv756TZvDo=,tag:d1LmmPl/qp0h051hh09stQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
