apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:k5nDLeSBKuY2PTCYaZ9x4yBdCHeZCyUEyuTKM+rXXDF6txQckhXDxrM7SCFiztrclMl1O/gXlUb5TKK4F1aNIi2Xj53UnMuW08U+8o8hm1VRTaOFsIGC889cT12F2KX7RsnlNXYyrSgiGD7CTf+zVVV4Ygk3TdoxQ4GRbUv4TX/FQRI534mqdqHoHdzS6CES2VVUssZJKQHxOPDpWK9KYELuzwzbJhT5LzSstOsCmLfGKtGYl9M/ITPTI2sx0WCGKkW2t6mKrWNGAP5rT8nlGMR6L7raMJjeOggkbaJtRBFPSqoYiYYPI/0yA8IWWVnDgq4GECBbN8GBYsleVVabjE8xfXZoeMoFEn9csZHvBsf8v3zvDnj4F6Z5UFvUaB4L,iv:XXTamMhKJqWlWq/Z0TlLY+rO5l8xlWTRHp+uud1/NnQ=,tag:98zMZ8MrwgPsL2PdWpvdXQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:sTyW6ecKGpfHHR+fE5gi7Vyf08QZK9PYujey6eCAW4teqb6LcQ6SheMbjHdYNtJnUlwvDK1umryJ3r+NGwhylByfQxxRbBufuRAS2UGuOSkAR9umyugoTUCTBufXorvMEzBYvleqWGVEPOBwTYTF/hn6G0KS8tXF0NZjS3Ux/CbQX4mBla8ggu00XC2bZnDvI4uHlU9WaENqR3vBgPgEm7eZc+824qGHcL8g4ip2quUad6IGKz7+CyHgpjiIJIhAOHji6kA6A98OvpA6sw==,iv:qw2eHAQckkBvntELTThICSg1vqGnPe5OWT0ca23VA7k=,tag:SNvQgcExEfYiP3zBAjFdwg==,type:str]
    known_hosts: ENC[AES256_GCM,data:BHHoRvrdq/X+RQ7Gs+AjUst3Bi4KdEOOp89DcQDLTFkKA075GsspMaxzZZI6ncdUwcnDM0J5Jy5LG4hWKMP86mq6UhmGEiFbe/jmtebDQ5AC3h08w0ndCtcL8VRXcGnMmIgq8GJsgHz14MkpbNWkA1UDT5b4yeyZKluYV2yQ/7qAUXp7rvBp0a76jWp3+Ely+yDsMgc16gaByB/2mazw4v/cHnOQZCMZwcqd,iv:3vlhU8dOaQcAg/O8ZNoHx58BsQWSpDg3CRfwHl4biYA=,tag:K41hrMkMnkr6fPDno8e/+A==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmc0NROHh3NUxVZWpMd1A3
            WnBuWFhBQW50a2k0Yml0NEx6bS9hUTFqdWxZCk9VVklJVFE0SFZnRnFRMDJCanow
            c0ZiUmFDK2pWSElqNzMrTlZvMTlDQjAKLS0tIDJDSnJBY2pCL3pGV2tMbDNVT0d1
            dmdmbDM2cU16T0tHUWRtZHBTcVpwQlEKpowzTNawpWVZH56Ju3cZh7CKzoS41K4G
            k42NjN17o3cHVSYFprd8UvRHdyxUJ25HEkJNx3mQozE3mFDq9F+PcA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T15:24:38Z"
    mac: ENC[AES256_GCM,data:0TgaJ72eg2eF8cdrzzWIastFL9IC3P/qD6Aw//GcCWhc0a4K7aqZq0swR1lA6x+ZrrOuVOzFCxTcOUgQk+41XvKFUKAedhddiUO1W01UBcnzmXkZVwHzF3aI/fZQJA1Vu0bpODzTHEu8oXebA8Yw3+RlXEF+HyuW4fCiBNUunfM=,iv:TAxd2lveeEM88wLLQrzK1aJ7jfFvR6U8YtHq+bQrOsE=,tag:TMuNr5GDwX6FV0Ddf4Lk7g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
