apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:LoBXccpfeLVjELqtokW+2SyGFTPoMM8C+6o04pKBDgIb9U42Ud07rqkRyB/E/DzWmuMVWIlxaNYYL+uZihUXPcG2K0yyYqGJUKH13yHBTVlmOG2SGkmwJygHxFxdS6+Tj50SnFrGpb1AxDVbHhGbp9RQEiK7/Sxedr3myyzLRNcscWlL74x3yvnlvll/IcVMCmbeptcgePVW7LkAElbdXCShc3HvkjDlP2VRXNm+TsorOcyv1YlfTx6v8cRYkiUzHlRMGwBLWOr2pMsVj5mz6ODuqaS9L24lK5FhwKBe8f326uE70SinYnZ+bosfrh+aaaEUnQb1e2fBNkozyb0k0IMxGbYEotwsHeMHMgNlpK1oK3SW75B6CHLiX0C4wG6p,iv:vKOWYdOEkwAJinl8UBdv2LFzZC95eCzMmfYBoP5Qv64=,tag:xUjgY4p4HQ/NM0584sKhrQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:fkRvvGvqTcJtJrbbMgjHsnkNKK34JuuoJ9hrX+6ERgTpqU6o8c2wNsCj1JYKne3diwErqCXz89pP0D3g/gFXWxpH4y3eVYovss+ZBGBO4l5ViKKnnV0ZgyYELQW5BMKe9upqG51EWx6B0eQuHRIXzxtnIKQXKeGHWFQ4mKFGMy+zXSfh6VwHaUE3ik7vu9zRRMjBz3V9i4sdemUyQp+8/j6tZIN6T3vn563B2wPbQ+XgobMPAnjSKBm0kP3+plSQ31RDzksW8e1/HkWpoQ==,iv:ffP+T7XecqJOOh9CSSo1DCHGcCoKU9HwQ/rfgCnTp7k=,tag:Le3QqippisodMINI/423rg==,type:str]
    known_hosts: ENC[AES256_GCM,data:qJNI1cL+W+tOoKrA6cWRFFIYWrFnww0TXFqXlzQa4+ylFil+5dgbYxCsg3NLxTdirNrzBaqcKM89yJ2zmV8yLY0GODrdr5eHk1cdadohq144QHuEFXA/PYYVvzi4dgO3AxQnnpDGumzGllGmqk+EmMuFGkshYk3wlMdbPkUBjwHygsjADktOnU8XzGGVmzP+Olkfs+RLGmVNi8yDIgXpjBoJZwgwLBtYaSvV,iv:HXdyuEfOlkPWpLqsa2LwxDk+LnSCYnY2Z9Mzm/CpO0s=,tag:tPksrbQgptMpvKlcllVA4g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBiZ3JyOWN0UytwOHA4UWJu
            MlBWdkFWUVN6N2lzMHdCZTlXaDBvNzBBQ3kwCjdCVUZlaUFJWUdnMWtTb2RKU2RZ
            U3YrVUxPY3RHaEg0UEZkL0N2SlBiTVkKLS0tIEtyYnR6dTc0cWVyc2FUYmdFZTRQ
            RjQ3TVhzNU1ZSk5lemIyeHBsVldHSDQKd2l/C9NZypZpD1cjrVajqCwLJPRECoFM
            iB5tGhoK/+F2OdNP78GWGVBtZmlROR+CED8pOQUaUb2UCXoHwbAwwA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T01:17:42Z"
    mac: ENC[AES256_GCM,data:jLV2WcVIUGtnp2BKQYJ4SDQarNSSmEoARgC3vayknvC7KrGNoLU0x3rSvE8QPTfF53+G5B5qqJpwdyiMTbmjPxI7a68PGogJ5vM2j6bM1LIc+dnelDhuxj3ODDophsvjuhnsuX1mAHgfdd9xb/3fXbQqM7f08d5dLsf/JYNAECM=,iv:pytAjQX2YFS9EtNTP1KjNQg1S1+ecxRKwK/q8UnpZF8=,tag:3jB+Zf89eKI/5IKK12rTww==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
