apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:KEnMZJ3h9QF/QXMwA+uYLWdwESC0bq3zVKrJQ4oAv1DZy9eKZSrcGivaHWJiLaygmCb2xBwxq/jAY2SS+UJqSYGWdG2LNOopRT4R9LL91rXojRDS1f15+1XhzU4DAJjnDxrTu5w+Xgqx2DLeZb0DnWSmx0NCE++7qecour4sUicUOsCCO1wmM1LtnIIMXshMRSIFvBBHWEDTz6UEaWoO6i5XJ4APvExNFbyeziR/ro0DuKDw2NdV4oiIXnLSvEGO7mT1gyhGmaviCTfE2hF2Ga3zF9sUdQvfnDACN9qnjKvjRGkYHKy32z5WKq5VTzoBVMdn8vVM5CJ6AxBKXxmcYHQixYDWgOsSLFd9rMKg1gn1EKlXy6Y/4KHkX2eVbbxO,iv:5BVjTfJEicgcejScWbzFj4vXyeSKs/TNnSxl08wDF+c=,tag:MVimpeMz3wFwZ7K57EQ5dw==,type:str]
    identity.pub: ENC[AES256_GCM,data:0ErPWwHTPZKFTkwXTCZvO/FzeNiU8i5H9RBXXPR8bfKM41dTx4JQJde7Mp+1aXcMeCAopT8MNw466JWnHQbtsjbKdNTbuNN4p5YefNScr8Ur4jauHefq5925ut/EBLQQdfieFVGymzXmI3T3fuirKqR2q+bk9XWR6yi+GbWy4xmGvQ1HQvxLzS+c2umTiS0GR6qsuIHd+9LxIfiQ4T131Yo07mOA2UP+uNSmCqnHNwkZ7NdaoaADQjGTgB7y8lpQ1BjQPkm0SQ/ecTXa/Q==,iv:sBZcqt3IWFbmQBCDNXVyxlLFfCi3KDLrwpAZhD/Y4Vc=,tag:iJ5LZTgOSL7j0WgdXrmrgA==,type:str]
    known_hosts: ENC[AES256_GCM,data:7bBzrfM8o3uUFFwJVHBYuRYYcGx0evdmOAfxxvT6Wn5P6et9evLElydEkwi0HmZvLu6MeVMsAhvcZh7/YyiHfZTLRylgaUGGkPCBZEXCbuOFDQzFrMYNmGn74SzqgviUXCK8G1F1JakrkAlnt0UhKr/saMF+Wr11pv8b9cdNUWuXAObS5YZtijVwNnYckgLl/MRhSofJxMZeIc3UATBGwTaqwAHrHJr1koeP,iv:FSNVFzQd60zRw6b+3B4U6Igk7B63zC+PpWr0MX8z67o=,tag:fYukFtF+54/dpv/d6gxiCQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIbzFhNXlkK1M2VWRMMkdO
            VVVKVmcrT3hPOHcvblVvY0VLSVBpSzd0YmdvCjFTNG5aVXZoYzVlU1FqL1Vjajk2
            SDFYKzh2ei9mZkRueVNXdzQxYXpkRzgKLS0tIGVFTmFPVksxamhPRzRUNktwRWNa
            NVZjV01VWFd5ZElwY0RuQWpyaXpQeUkK0jcVuQAZakpFY6Po0IP0cNmCSPvNd5Bt
            DUiTOyYXalZopKGiCj4hCWi1Ws+J0V+a681LbyOSt53xmg6GhCRBrw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:29:36Z"
    mac: ENC[AES256_GCM,data:3Q7URYvpcLqjfpdixwCDjXUzWPlL9vIU+AjrO9bGtKXwhIZ93aQwUPw0TJVlIVBDuc6pLg9IqMKmf71uNOmbDZ78FLD3Rdois3VdnRUCJXZwO12S1WuXha+ddTu2Wh1GGGMX0gGFrIJMhpFq72aEtZJKzOjRlCzI3gnlm+80ybY=,iv:R+js3dPmjDc8DUR2Tv+1N/pxa9S0ZSUTA4NVw+5r4QA=,tag:/Z2b3fc/ZRvkE6QFigXYGg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
