apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:4WC+q9qBeKVs3qBwrmXXuU1vGWUhvlbpsBWhoILalkR4byZ8cNQUYFsgmrtIrqCsVrkD/TODLjKFsiHlPGAEprGbJCCDRN7EvROLPKVlNivXNEtuqFqM32Lz2i8LmTrWzr3b9IVT2weahkl4kr7DBKGi6YKzs7IVhlzhreRi3x0iYG5EQj5uVzPOS3IBEVTKHetMKdp6+563pf5T3X7x22HzRHkY83RmI6P3R2J3WlzijGSOXxdW9z2T8Lq/n9tzAx/pU60eDvxLZgd4Ec7c30ABYjCl8dGYL8ckzxHImvOSEXpWGeCRTIf9Ta9aZ55Xt9asw5SCFAjy8PKL/GyQ9HjnsQRvWCbse8C5rrdW00AGTaHpC1DiWl4+Tr5hQSua,iv:M3eUa3zS1QGI688JgJs3F3D/tD2T4JC3wdPeZQdEBD8=,tag:pDYfhJkJc7fMA3VrGe43Kg==,type:str]
    identity.pub: ENC[AES256_GCM,data:99aikvvpynALEOkbyGAja31imLUZJYyszL4sCmTVKmRTv9dlI6YETnu0EXo+SAU98mSEB2jOQ0XkLvSCFoLVM69uUSz/nK2mbhUTnnP7ddDpj+jowGM9HgdDJyLuh7NSMbA7l/e9ZFf0cz+C5IDXnOyHNRDuJwo5b9KhCJOI+b1cyZLI7kNu2fU+SoVF6a6yYnqo6yUZkE/c/GhL6m5ktaph9OJROQwcDDWvW8tTNkb1Hj9p9s0beJHgbMx0FRrRW7P78OvngOzMEvnFzQ==,iv:IcKDl4PauUZXpDjmXwr6scCSQfVPpb1qnHXljXrjAh0=,tag:3StOI88TqQLy0la7mL+aXA==,type:str]
    known_hosts: ENC[AES256_GCM,data:N8JH2XbcnVStO4XQSlMxsz+xUaBX0Uv0+BdanDr/SiQ9Cx76V0y8CelwRBJI9+DfO+y1ZHvIvJT/YHhWPncBB8qTjoaWKPZUAwJoOQrNJfpbS7Ip2WR/i3p47AUS/T5wua2Etb/D3dHvQfSk2OZuFVejlSnPbu2F4A/jBkj5QL9lGBL98QXJ8QX5M3toh1C+A4LKx5pjwKjxBZettnweScIPiK5Q6nBgNjXL,iv:iDuN7W59OwoJ1t/Fi67Op9P4i7MOgEVj0A8j+b2MSsw=,tag:mN0+TugNyWsSm43OwrHlRA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyNGNJdE9PdFRtVWV0M2lr
            YzJOQnZPenFlK3d0NG5yVDdJeWttSk5Xd0Z3Ci9KK2NKbGpDQ2VRanZwRm4vU2wx
            amtHUWVudGtyNldkRTFqUWFEOVQ0TE0KLS0tIEUxVzB5S1VRY1F5ODI5TDF2N0hu
            dDJVcnpkaytNekp5YkNxREFYS2hWcGsKwO8llN6PDOrYuayCUxbVR+TZZf/XPS+a
            XRqxWCymQ7g2SvVrxZFy3jYH8rK/Q+xjRgVWhqAK4buaeucFSnE0mA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T01:16:24Z"
    mac: ENC[AES256_GCM,data:S7+qD2soGdlmJapBi/gWSrpRwmwFGOk+Yt463bHqurunC+bCwV2h/yWc4F7OcG9R7MUPZfy68FmBpXfddleoTZCFzfnLPY0L5q4Yq4hne7yGB6UWTD41MddA+qeD580DqY2JphnnIWk6daGBBEp/+DjzQklDofLXWQ6bteNbywM=,iv:YgW0VVktImDeMFHl8rYsUMWFmeit6ftjOw/5mOSkiL0=,tag:/3T7FJtS/VVz+W/MUwYxCA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
