apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:uKAarBV8l7bptbzzGg+hmbROMfzXS2Qq7jsTZk/63qa9+zvcNAy7KVRRaa57R4Dyh/gf+5KxUNFkTEkmzDQNeQNm/5hDl7PAFIbDzo9kZkKeDoHoP4u/X7Ev9AwLFwBFvmpEDYzIRIG2Ap3VOOaoKst9uswZIrIYp1ovFREc2jRib6M4cPbpCLuSpd018CPLXp04aRMycHVcbkU1+5X9EMwtTii6OmGlJ9v1t8yPzzyuLj4i3oha8rThWOekLkVbF+TtilW+MY4KrowU7dRgc9FYFISvvxSsJYz7keF2vUlCB4PEKYWWoomeOC+44GZLe2tU1WcUElLLsC/XOrvQxFviH8+9uLkVccuUTGE4BSkkED8XrBuwTK27ZJ/flmXK,iv:l1nR/3kTeVG0GDkyw4va+N1y7kEfBhiAI0OLerw7XaA=,tag:rJ08WmhZmyImnvRvguezug==,type:str]
    identity.pub: ENC[AES256_GCM,data:S0dKb1D3jsavyR53qaxkn9r9UQ6w+PLL4N2Verev/OWKikaQSG/aVvv8ZLqgqQQ9qTWRo+tH9l+8wRBliGr6KCCHx6LDYQ6iJtijU6NJv3Di8cNKnfcJm22SfeT1QPJ9cfAB7kdRD5rDY65TTXfW9vYmIwjPxmjas/+H0X7Z1Fzz4Zic5EZauOCzebSQBSQjvD1on+lejRnOUzQ9ObymvrH35iDPAhVqGpxtgpCxriwLlCsXJluFXAhRo10yyjcEQvGrgLiaqZRX25pNJQ==,iv:cnfp47cxapajbZCj1B4BFW5RPMWqrsF2fw/H6ph6DVY=,tag:YwYiKcD/BlDmxpw+H6mePw==,type:str]
    known_hosts: ENC[AES256_GCM,data:Fap4IxkVGrbXV+e0bZO4SkQSaKGzmBravnjB1i4AsWUiksPXhGQvIa1qhLT9Z8/nw1NjtOdWjcqvpwA31bCdxBqAqtIYyxcocSjLdhhsWMOfzaZ995kgMjC/9iKnT0Mvdw5rgCJ7DF1i/H5h+GcyDiNX08rNHM0Rr86rKc/2RjXIMa3cWdSHSsavAEGivFklHBgGdOTw/sEA5joE533XVyDfVwlcdZOYEbOa,iv:+LdiQ8k2Y36NDJ6agHq5NvQTtwc9Tbu2zENbXq/Na+w=,tag:5AtwRu0YwGd6dR/erjIrEg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBpanh3Z01XdHBZcFI5N0I2
            ZU5wbnpnblZpTzBwTTBlTDlaRzNKdjRieUZzCnpmeSthR2IxODM3WHF6NzdKdURD
            MU1BdCs4V3ZhT08wNE1keHNKTnJTQlEKLS0tIHhySENSSVRST0R4MFFXYlFudDQz
            SnV2N1RXeXZkZ003Zms1RWkwNGVvVTgKmog8NyAq2WLw5P87w8EnEYgXuS8M1LUk
            G0oSCHtdbbuVR0Ty0idVnAg7TWnfBjeh60Tikc+cV66hyz9PdpTjDQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:23:40Z"
    mac: ENC[AES256_GCM,data:nqwSVKQmduG5q5C1K9PdJcExbat0ICiNSxBtBewzHEz0f49twfca9IIMIo8PnUevLbNW8AHs8bACodX5Wfmyacn6WKxjKI1EtBVT7flcD66PMN91ZgW1HamQul2VbaP2BaQkUDFT/wIt1zHcpg09EmjKC1J0V0yJNUiwmYrGQTI=,iv:Uph+X7dWbZ4rHjzckBYgcE9ULgYeAbVMuhiRdzpm0No=,tag:DzKAyuA3oHjBMAdfV53mzA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
