apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:2FvFwTmOdN+R4cVwQG9o8FKOnaG921PfvpyP6//yOGpyEHfuZAgJVQKG7oFcywTeBDyk8YEQrRbfXsfvvymaC3pI//F8r+tQcHnhpEZkMK6Ubm0yNEgrecN+YM/9H/DRAQcm6WW46QgbalGsJz2oyxZs2Fi7rcmiIKrLcwcdcK1gu5EBi0mp4R1kd+vEqqDwBC+ytQj9bd84dnlKjWYzFsi5hxr5pV8n2OoZ3wFfvwI44mp3VBv/F5aIBlvkMTK4ESxQDf4JW+gBC/ZdZeiMjztAndEdeMup7i9aXbGyYtBDM4+CKHJ/TCDs8dXHIUblLgsSuM/+bZEsqxWiGMG9JhaJwMbnynyi+MCVB3Z/kW+76LgV9QaYPpprx6L9D0Ro,iv:JR53f0dtn8uVLmDm3FiZcWmwf3U8QPhSqxHBbHsz/gY=,tag:cK/NSLwlc24NkV1XpiJmtA==,type:str]
    identity.pub: ENC[AES256_GCM,data:tQqIstBAV+HUZrxF/2TGt44Hg/RSFH5HwUcC5ecrDmVH7QxnXPtH+6Eu02eRqk2qL2REHdEsjhQ7+pJSgQm9HA/+gn95bmP5RfW0Fu+60dvmCz2PKxk9BuEavpvDje1JR1j6+fIB73RGuKsicEQbZjWeRG0wp6UU88+K8PnVjoqhWwwxG/Wd608TsYNc5lXrHR8gCmOl2ssBHPMIvbaeh0bFCKi8o/qZiJtxzhubcWdEEynS7aF77PPplmuRIze/qZOoOG/DutuvtXXoJg==,iv:pl3G2i14XtvUb1fF2LhCnnWJqOQZQP4r2aJQoksO4Kk=,tag:hvHow8HwlNcJJjEUMhwr/g==,type:str]
    known_hosts: ENC[AES256_GCM,data:aBxi7IRA+Gq3t68lQAGmPJR1oafb8WauQdy439i4nlnD5VObDryBBe6gdVrqsjJ549PBtxLjyiXc6rwqfNB9XS51hjnAbr3++ZQsneXVlAwEJGgM1vybtlQFgW0eLxr4TlvBOGT+NfgCBKi25RPFhpiTCk8cTnowDkyEHEYC9+qMpaxBInxJX+HI+HzjjpJs9+C6JeQbKfDzjHMkbq8OdBz816doHWmNgsdt,iv:WCbjt6gQdROVzXmkzEneXPRi2/nhn2K0wvc2hGT5Xfo=,tag:jmO+kMX3wI15wvuz4Nm1DA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIZDgzU3ptUmFFTHVEZ08z
            REVybFphcWNsU29RZUpnRWl4VmYybGJJL21NCkdvTlljUEFwT0h6QzNIdTNkZC9n
            SkxHWk9vU2Z1aHltWitySjMyL2l6NkkKLS0tIGhJdkhldVVIdEFOLytNWHNVZ05W
            dnNrZXJKN3krMzZRQVNBSnRvRlR0c0UKRz3ZBcN7vnrwIEs4LlczJkVJOy0YpqYi
            8KZQpJN8hfwJuRD541s7cgwgby/Acsxg6HDUuwqmKarOWPZCb1EwIg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-29T20:18:41Z"
    mac: ENC[AES256_GCM,data:W+MXM0+l/bscCzDw2abXzF6fsHsXCWPzE/FwLAzWVDhw+JM/XupcNATHgDHKaHkV5zFKi5v4Oy2DATxJN6qYRFE6qwehmgHLUSEHeexPucNNUoaUQHDOa7w8d1EM3TCleZcStnoUREV+TmY0D2Vl1F+ucd6wMEcpLze/ugkCH08=,iv:HuOmoY7Iacj0BbKS97Z6DCRJriB4u/q/u2FiO21qccM=,tag:X0+N8IE3UTaNk/10nhiHLQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
