apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:sZuLHtPB3rrLdHLVh8fR2u1gsjb0FwZMUUH9Ap212nNsbZVYo+rxliwe+DavEKtkQW0b3EfKfJw4WrYwVeaIgKfQecOf/mMkwy7kQ/QJtIKguXeO1epusSR+IoVC7+CD4kpFYTxpNlwdxSdziFYxUwDVH9oM7lKQTzPAYYME0HfJlRCKvzEBi+iuQdisKVVsGNrx468KkGx1lkjpjI98LDhn+XH3eAJk2xVDSmI6gcFBAiIHqQmLc56ftxmMJeQtbRphO/tYQpm7D0NUxxHZRv3aBcf3nf0SZBYtB5H1Y3QykHpNk8Xp9bS37gQ6ZMjOSUAMWvz4R85IT2Oml2PKl1viRSvuTP5E4F3heGoUG+cwZIJFyTgCbO23ZoiQezql,iv:yjpXRJhP1WtaeSNlOW+EU1vnHgUmrCNJEwlaJq89PR8=,tag:SAuXk6EJReqMFPnxTRDjHg==,type:str]
    identity.pub: ENC[AES256_GCM,data:ZrS5SX+4T0+CpOPfGygtmRZrMvl3OLnkT1KYjAgIGf4fCdyBT+1l1BUwuDrnbJKvdOxEnO9/7tYY6n2+pQWBHeZzHz3Q366SvYcoRWb0rlvv6/ARcMsRk6dwVmJI8sDNzRUmNQXw50sSZSsscqQkmqLY+hNvh+mCi371OYadvG+iWnyrV5TCd9jC0rRTpH3aa4gaLHAh71WsFWgWcSQaWHJMEMc/gJ/tTXFzGht+Icekw1XG+JNWgETQVhaoolLaeE66n5aaSMxbS6fvfw==,iv:89ENrahHJAYtc/UQenwUeyFTSD8vgsD03jVhBvztrF4=,tag:t2KGI1M5NtjKruaWezyIAg==,type:str]
    known_hosts: ENC[AES256_GCM,data:S5EMN3aqxS/1rea6uG97xaxaDJgHHWNlhe5o6hSlupSsdJuRTaXrpKWas3VN/PSlAG9VrlwojGhR/0VS7Tnlu9YIEI3dP2F+2rmXtVkaSwsdDq9awN9z8NnNEWGJ6FevxFA1l3Fo+3iKQ4CF+AGOdjw3moeSufxXpiesHIJQmdsjGlcE1kv7lWo79qr5Y035qHjBdd6eZrlqpqAe48Vfwpfq6UlV3nCvpjq0,iv:LEmVZHemJqha6pqnB8pnn6e0Yvdqt9ldz59UpsR6w0A=,tag:D/cBEMrWM5LkR7LpTMctZQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBYWDU5R3ZPb01ETXlOQzUz
            V0RITTRtRG83aGppQlduWlY5dmZucXFaVVJJCm9naXNtM0hKeE1SSmkySjZiSStG
            S3BQK0R0dCtKRjRFSHN4UC9ldUdvaGMKLS0tICtyRno0RXpFaEl2UTVxUVR0TC9z
            eVJJK2wxY1JLek1FMS9yZU1GQlVyVTgKxB9Gvceuzs4wZQOIPGZcPmtZvI4/8AYl
            H9B5U95fF6Gclw1gesl0F94Q8hTXwj7ndl7T1bx55+2hFJdFRwRhYA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T17:39:40Z"
    mac: ENC[AES256_GCM,data:ECQ30Ykd1xIcEpgvsw4XnoECT7u6lIXe4p2ntZfq0l1plz8ofv2kRWN6YHomFXBqWs2kL8jO10g9QIcBoTPZdDFssSfWmhC5LjZdgDf0FXa6VNons2WuXbK7SDF39gfsiF+tDY0Yf97RO06SHUNxCz4tQAqy37HzPJUbdq2BonE=,iv:0WkbZwRZ8kjVt3wWZAuPQJ6SP0iCvFWn+tkfFFx1PgI=,tag:/eThW/gWeXaP6svkrfsfKQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
