apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:PNb4TCeGSJLv2UBIV6kDheUOXgY4GqXqd1WT0csP1roAilFU5c6NWfF/DCGTLL3TPYMLGGO/lXocBNdWec89FFXpmORvtNECvkCmPf2bp7n4BTbUJwq5HZvHc6L+8S5/OXJvyOLa6dbB44FNbLnfrdLlyJS1C6sjcnrwdurocBVoDMlIonHKkyXLKue9Wq57YUwwxu7hotuW2Yz8//38WfuYTzZAJKSWxEgKoLSaDmobe0QWZXVU4mCa30OithNL8bhoCqbKAFzLRS1GhdEV6nb21LpJz4rOJs/G7Y2KGoc3iAWTQulesk9OBfwsmO4BhpH3K6N0nPQK/1FjAeFmBWG4eSj5l/yUzJ5rDjwHvEVbVqz2JjFYxUgXr3bo/uOY,iv:xob8ntBIlqtyBLyLXln6Evj7cJE3uBVzuqAiSz/p3SI=,tag:JVUU/Pto90RTBlibrzvWKA==,type:str]
    identity.pub: ENC[AES256_GCM,data:gdI9AKPuOqdy4tg75Nlgf5EIowt8+UK+rVtko1miG5c2nkGEVdoHmJJIcfqq3Re3fmiyHsUAe8z41nR5fXFYjfNYbEjSG5xgaH8WHDebpARWNs0dqqh/0jaCzsQeiN76B9Tt5l4GTg8TPoAzjct6ZuiNwuEQ1ki/mcSeCnkyZhnJvD0uGAiZUbVFCQL2mNenRo/kvKAxcWJnplqyjgVcxSkYY0s4SO8AAi1xc9jUIRGoayU+RSU+V5FvfXydKXqAg4VhLukU2W0DkUacKg==,iv:tJQL4DfwhQkWkI19KuIK8VS2ARKVSvKiKzigtMMbeP4=,tag:445dWXCwYeEETZHCbR++ig==,type:str]
    known_hosts: ENC[AES256_GCM,data:svCxqnE0hlEcsXsbAGRPoULLQG84qUY0YaXdWM1vIW43W0N0oPPFS1XuuucGaGrse3MpbKwd4xgp8oFpJtlQvKhOqX1++isaL9MCzTMvE68/zd2V2DV9dpDyeVdCXDic4nm51JCKKp6mDd1P8cf1frxUi8emB6C9U1XOaO0vta/ZwyDj13u6rz13JBDeSw0LIbFD0lqaE9o3w9EJbA5MNcYKAr/QOy0yx+wt,iv:fUuZ4LlU7dGF9/dAS37TbnqyW43/YigTdttF+NJC24k=,tag:Gc3sojNBaV3gE5vxAcI3cA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA5czR1dXZKNmhNeEdZZm5O
            N0h4UHM5d3kwUExkb0ZtYVM0UFExblpla1dJCnBmYVgyOHkybE5mbFlUWXN1M0N6
            QmJXbG5SR0hteGxLK3hnUXNBdjZmc0kKLS0tIGhEUWpHTzNVWHZFYkQvVFlQd2VT
            eWwvVmdBZEFNQStrSFRvbkMxNUhiMkUK0WhUQm1AIDCnW0cqHokzrw/2XnuwoteS
            3j3WDSEAaiMfGFT80zueq/gVnydzLOnCnyDt1/JKzKW/ku8196MDoA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T18:59:17Z"
    mac: ENC[AES256_GCM,data:lHRPOagYPx5bZnf1wq20ux1y653+g0JOVg2/wEBNhzSLOVDY8MP/xMKC59LK6roA31uy7ud62xWfFi7r49r99Kw0hShu3TDFi8+oR1kBlU1KGPqgi+6efxKhFLdMEy7tSY5i0xGOKV3EkH0ho39ghHXLPDfk5+rYscF2dRzUWJg=,iv:qIIyePvmO8VPHoQvznlI2ARu+0P5vslr4qPGm44wgmE=,tag:xafxPEOXj6gFd2wIvBOGyA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
