apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:7PsdlZ36u9YkfqfgUeYPA+SnQgj9jetnHc9nMMYQstwZvNi+3i086PTvSwbVmL4qRc/DbjSwDq5ogn0DgDNd/7XFuzsZLIjOstYlj14ObsNYKsjVMnVGeSNT+BSWqrVsCRge6bTrG2XmCnQLThlMFNNzmONKPF3HtbmI3MFUv1kSSc0wrKOOvoZPPAAcvxUg1rMSr1Ec5jHliLVuCoPX6QMxBa5UFGTIopMFucDJjaCi7zEq3GvhZVslNvnbBQU0gEj/bhl05Owz24gOWJMpGQ4BdZ7yfYMUCASHiVUGKdd2nrmpXucOd1MbcFq0l7QeOkhWCAa7sedsZcU40jWQQTTHexnkDhVvq74iFq9nljs9/91qjzbxwJ7JhPeq4RZT,iv:fBuMTISFRx1ZO1w5LAphgJKI8YQlyDVTq/qsWG8iLSM=,tag:rvjGsysMJU463Xd26/6VQQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:aGgs8ZZXQuvHEfPBeYgqdPXocwayr1nPusOEj5pcxaGFHkWbMoCrf6/mVb3KPG9PouKJ1tib9Fjr4E9kR9HJgBaXpI9a00cKdlhny5fY2E/r+E9/vIYZWUtActtffK42/lTiMyxBuTX5eWeb+KUw5ZsSDiHu8T/ntOE8MteR5DH4CuUv7JdOMtBpZ8XKikSD4gH+9LiUlhaFey30AJb0k3GQFYACeMB0bV/sATSDkKrSbIDtb1UbLr7BG9NYq44etyQ1oiLN7qD/8CREOA==,iv:EbNokel2cFVmnSd/pojME5tVHdUZVXiqSkUAH7w56CY=,tag:OQO1KWU001lcOZp/EpFdtg==,type:str]
    known_hosts: ENC[AES256_GCM,data:+nxVTx+Y2PJJiDAbRLCL3+T6M5S1oUBWqBWPawJFaT5+qVVDUtSZlP+cZMp6qXBUgd59EEo/izttoil1u27jKcHbnnBHF84CUuEKkqmfr7gYGPcLkWDSRDd7sJSqF7DkyP7TLe+l85DXo/zclCWXa3yWFDdQNEl66sVgmZB939nPIcDWFeo3HCvg5q6bnFeEtlYpzSJc3rGYzmvpt3Ri6ZOM46ycsn+4ax/K,iv:Nv+8JVeEnBGlGD3QYEeMKsFAbmrINioApWPAveHRqBw=,tag:sBYcOrxRIdiVv26HJE4rYg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVQ093Mi9jQUpRWUUwdWJR
            dTI2S0huUkRzU0gxWm1YdnZCYmRhQ3NVR0dJCllnSEQwcDN6S2pETzY3bFJIWmk2
            UU1rRUIwV3FPU2FLWnFzVnE3VE8zWUkKLS0tIDdHQVBzeUxlSFBaV2ExaWlYWWp1
            cGRVNFVxcVplR0E3L0VOMjBsVXdCRDAKsrv/x/jFchx258IeR7bZay708Aadaf2S
            6WEhUMHw/Bvt+mI0Gkc+fnqZgbgkfD6CNkt8NKWiwDDlYnLmx8mrNg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:42:23Z"
    mac: ENC[AES256_GCM,data:7COznhJBlZGkIMkN4YH95Xy2+/G+vW52Rq7ZulPJpnFpFRH3FS5jDE2fpr0Z1IeY8iO41Xeuq0vUEeGwj7szUfAwTyn5lHdN8/m7Cy+dxeIzBn5FLn6hh94NYn81UhoT/kGiapuXCIsrBFKd/wkLlETa0vOOmztpsIFbRoWGoBA=,iv:a+eVti79aWQWRynHtOueaBxwy5UGLLEu2WIyvjh25Go=,tag:wVzJbhOprFSWEYBb1HD0lw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
