apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:mXshIuWtpMFT6fobUpfI6vt/6SzQ+tBHBJJ345LyiiVON40QTU6XfYQP0WSTnMbVkdgwwvfrWDqpPjAZwQk9RDHx+TRrqnova+Fb2YPhdvr+R9Dm8++XgHtCOggkHxYRJsLgUKsF6asFQOV93/9/kyBa8AD4QFMVHdZkhclMHjCgKvl/RfPDiAaVcIe4w1aWbnnThpo3T/hBc0jFMrcN3LfpsXlRWmWKZ+D9+2Uk/4nYop7YmMJuiRxlTvVzm3BeZQSyJ5cGrJlBsSdDiAVFInYoNi0fjKsWPTod3C7VYyiNmEk3qF5NVGkNLQSwidFf50GMyi5j797HvL65LizILPAsxw2eLomw+CYvlpKNg5JVkOout2tKRFWhaCMztpHW,iv:tH/wTeKpEqpqyl2xMEdkH6TeoM7gdUT2JEWiUVvB2DU=,tag:KYCYrtbSTUC4DahqW75/Jw==,type:str]
    identity.pub: ENC[AES256_GCM,data:lS6inhxluszef2UH7+7Xkonr1pF2Z4IzWr9Bt/uCV6n81uMu0lGX7FKk9uoRXuGQJmTEb3YzIvT+fAOgKGz9JwXtyEyRHcHfWQ7Eh58OEMPK3y7BTrOoPuRq/YGf/htIFglghr/CiNg8+QZFG2145KZb87uPBcArnonrhzueDXz1eWJsyZCFAN4Za7rwXPGIjPuSFu8MI23haMoA/Jd2OHRgiwkxGq+yhB3lXwQfjHP+EpxPtLRJkIRyW7xuysA7SVm96QfUBm50uN27eA==,iv:79KBUCcQ/A8Yer+keBqjQWuMKgt0/H3YWiEYAbXWotY=,tag:9HFpsxQcE6zTMzUrwF6C9Q==,type:str]
    known_hosts: ENC[AES256_GCM,data:0op7wAmoV+3jICptnKGLOsKufn3ZfOwMR2cH5OneiOagVjqode0sPvmqmN/z8pT5w4jVl4/89W2b6ZxAHc1nc6WAtmmNo8aRaBaM87MVHST1ws8zaIg92rZRVtrHIf72heYOylNToGq1mk4Xs7/HxalGUkOgTWIjeaHOJM3LloORGvDHv9fJo9Cu4eXfzSJxx5JFo1Auj2echl7/ydWeyW+R2RtMMiFLuJM1,iv:8cfBX9Lj2sm/ZUuemZ12AMV4bqaEmnW/zUmfX9NJ5uY=,tag:NBeNqTI3b77tRu+5RvAViw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAyQ2c4TVpKNURwMFA2a1NX
            NjRyM0w4UmlyOVljMnZSdVQwZlg2aXl2ZGlFCjBtTTRiaUhwT0Q1YUYzdFhObFJL
            ZjNjakY3Zy9Qa2FCRXhYSTNRbHBCaWcKLS0tIDhWM3hSSnA4ckhGVS9XdXZjUHhM
            RWRlYXVsdk9nMjg0ZWRKWGlSTTYraUkKgQLdQP/72ZAitUdsBLmFL9UymmOuQCvT
            2gFLe5degKXOiYFfccGidz+YvK2+Cw85XGq2x1XE0PHnwW95PzVGWg==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-15T02:27:31Z"
    mac: ENC[AES256_GCM,data:DNtfdoK7Yph1IfcCVVyRuZKpbDIHMWCr007GJ9ougoJHn7qidDOzIjHhQ7LGpA6cUX/kChpj7Kk+ZBnQUn59cQR71hLndsnA+a4U1qdDsG1dc+LPOiF8H0w/2U+YkMuWWFJn4C8OctlIkS8HXXanhIlvGkFjhRr20POu3BMD1XE=,iv:HJIrIVA3Bq7VYIbtZP6zp0ggQ3HkTUAj3rOIDq6LlsE=,tag:bbHnTLCun7kEB9PmyMbtxA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
