apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:WrngpsKj6xXq72eVWNx3YD5l8Fok5ABEE4n0W0BFjxL+UWwDrheR/xElJeCwWypCv7KxxVT9edcU9LzIvmZIjnEIAmQlDkVyxt87s/HDWytacaNdMbOmJK98L/8koJnTU8JshonRwrjKyd7IzUkVdn/dMvS3+g0Ioa1fiHtpnksGA9J059PhgijOFYu5ltb+BTDNjk8C6NI1lrsPOrlBnhYbNQwM2Fc2aHb9hkrhylt5DkOjBCH29zU0a9pdyJHrTx8SrRdTpLwC7d87ZVonchaue/8MaMuAx+6tU6LXUzjKss6lSy4BoK5bZ9myuSc8SLCsqdMTT+vPEYaEVD09kTFrMQY9rTiyaXpGe7WwhGK/py+Y3N+fhY2/BEhLixox,iv:8/+L0XCT+MNTuL2/BuaPYSRPgbVVySDBxiommqPtiTg=,tag:Q68zxx4WAvqbXhQJ6YUvhQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:V/tnbsjSg7E/nWmnMVyIdCYYO2IQGLI9OzCgCNxpGr1Vdo1oB/54OrG7Zvv6Xb3VDQzxhly5nCwvQbIAMuNFoRignOQkAmY8F3H7hqR1D9bCRT3psnxzGGwhfOHHFqYF7nVtpeERTews/BqqRgpvZEE94tsWkQRyQ4olHXuRDL3/TI9vFG/GrXsG0Dhcmge8ZH2dYYGb2jZxzOK6oy45/m0Byx61vWVI0XPt8diTZdWX2HXUxsabIsIO9s3zvKIbNPwqR8/jjXnpYA9HcA==,iv:b49qYJ599bHXsb8BOcHsR+V7snQHGdMC3Q9azisKPNI=,tag:u+D2vM15ozvBclxDaGG4xg==,type:str]
    known_hosts: ENC[AES256_GCM,data:wfK4FVmarstOz37xAOS5zoE5jXOlqcD22go8Z42N02dEm9wyUWWaptW9jFPE7MtOpgaKFuEqrWmUR0l4QdGbQa3ZEQsyLMorisYP7JfqrAtNRYEzcjaw3n5T5kwttmTBth3r9bv89cwHa3D7hIhPb0ZbN+PKrjyiynyMrBBopMaSAn7vgbEwlcI2Z6qzj2T58oT3NhMuovADC2sVQnhHQOd1ohPGw82xoquZ,iv:ZP3u5xpnvqDac/VhAFOjMGOlC2KNnpQGO21CMgimPPE=,tag:FoDKV1GLtYyR6TY51BUjfQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBucHpUSVdCZzFMc29jTXh5
            eGQ4em1VRjBiR3c5WTIxVENGdnJoSHRwbzJvCklHNTJETTFEK0pkM2J6OExtNVdn
            VXlhNGlZamIxVEFuT2x0bXN6aFhqT0UKLS0tIG4zdnVjaE9OTEtMMTI0TzBFZCt4
            M25LMndnS2NyWUJscXNYWHRReTJOWkEK4PlATu5IiCEeNt6+97izhifkrVr8donk
            3rPKJHSOm/DXEafjvd5Yo7K/shYgZXkUDkCmbPPr24v+Af6HV2d8IQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T19:35:21Z"
    mac: ENC[AES256_GCM,data:vap4+ZwHN18VDWrkutk9FF7j8fKiPftSf43mMA/Q3I56TnmF3ZvDHbEBxS+qi/5wnN7hoxq1wgz8JJS2hb6bz67s6tqBdIVeANQnUpEhba9G5QQqQV5f6jP/fX9icqBF7y0ApystwEYz0qpPE1qUNi3wrleexLUvLq0vOSCMBI0=,iv:uNppOi6GfDija8dT6rz7zCs8+yixCw0+tKij0O4kaN8=,tag:hnaS2hjSTk6CoV/aV7Tb7g==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
