apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:/9rYE1rjXm692jaXILOFBMmN3kX7lxa+laQjS2YyXOyUuD8G3KNTcCY8hG45VaM2Njfd1pbq5VTq3BCTerkuggiutZ4MdbejaqmwXgNxakSZeTDqGSRFGsAhP9da4yKdrAVietJTmglLgc8N2s4OPlaGRgRTq8UWJucMd8ilJZB3shzU/DHz63iufPiYyR02YaDKQOGkUQnDFMRA3MEMPXRdlFo3U8V/DB5o1Hai52DppivI8KRgS4lmqEFRgbQfa2Ade3NWJ6dL19TAFJ5HfbPrm18bHR3YwSklama36nsMRR7dtHu4NABVHPp37u88Paprt10HDfeUMkWAeez9LLB5tYRtj82+I15NSUL7Cea0C4JQi+cL6vACRaYjHVbn,iv:jDVSuuVl/GLVxHW3ToAGZ74LvLXk6JygUQwSy2Rq5t4=,tag:8SP5Jc3jh/XKCoZiZ6WlpQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:Bl4rLzAnSSgM/O4p77isASP7e/pcce7zI7W+VrErX2WbUe1zX4r7QtUa0IfCpDkK+SJ5Or4bbctQWLpX6aH3nh1/dlvRiFE0euYnAcgBMp7FVBap+Zi4VTp9xGALK2OPBzBFmbteUgK8nM0p7v9F9+yjGqtptToPMPb2zLVjHNcaJA2/geUaNdj6r7YhCrTQtNWdbZUh7gF/soxQtfRBO+rY0GjxbTefDtruu8cgGEgcD3jxqflxkMFNALFcccfTM2Z3TiBwhwUFAL1r7w==,iv:ELTVyPsT1Bo3q7yxAu//fh1/vq4ikCWeT9RX6Wg+Pgg=,tag:h/J+acVgjVBTHr6S8TuAWQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:RcZjdK26YWrIR9TNtmlSCSjvsxzqiwRJp5UsFgcukOJP85sUF3oL1bK5rp/ZeW9Qn9AXPuhXo8X3uIM6BmC6gO6vsPy5zPQjw2EpNUIROv4/E0/4yIGo5HZ0LQNIa/2lVS2W3OAdRK24vbtGFcdZOZr7gmoq7VNGnEzGs2ZZay8uqi8suHTZpet1vHztp49LzCNhoZmYgB/lMZCsRmIthB1NlizgYaX2riqC,iv:wRqMk45bdbbJhU5crl8+UR0Hjcx0Bu9/YkP4vuYNgcg=,tag:u8W9vstp2IenrKFR32c6Fw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXZ1RIU1VkQjhzT1diNFJJ
            aDEvaVhhcTBqa2V2ckxQRHl4V25lMGpONnc4Cm1jN2krYkVGdUVxUlBDdWZqUVpG
            eC94MDZDRy83Ti9mZ0hrMW92RTlIcncKLS0tIDcvVWxVQytFcU5xYjUwdHZhdEVF
            ekhObkJIS2J1bDA3TTdydUEyWGpxQk0KxQ1UykT0erKKvmzgF3BRLhk3ojiHUvT1
            uZiUHvgMQXGp6XjX1Hwad8curUojGMBcwAhrSarBJkuAP3UAql/GUQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T20:06:42Z"
    mac: ENC[AES256_GCM,data:NTHnrfAAZlGJre6Hh6MgNy7d2iogLk4wHoopKAWxEO+pc8r55SQc5bY1m3o1xG3PU7ZaBJ9Uiev7U6wwJa6WqlCZXj6Quo6JZAGIopS0IzpkRPah5NT6bcAXvVG9q639LwqtFIkTwHEHxOujRdSdFd1aRS+UleTljv9eCLLId1g=,iv:tDzT5eR/jsWHPkFiGKHPlt6HvkBO8Yljcwb7GH6bnxg=,tag:tfO9LF32MRsJEjx3idVGdQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
