apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:x8AonmDyayMn+Ddm3Ni4OGvzvd1Rt9jEDOE2cZ7N9gKzlbQcsDdrGEnzbC6AUGYtPGtZr60UofED9atP1UQP7HEBTdFL5Y5WTTEjYJ9VDjU7vr4QHIE1+yzM/CZm6xaeKy4+sRCmavEsM1aq4NN3PZXA9XQgbVsMqMyBC3HfOwlt143ZBtikeBNMYNU2hMyFzpyYjiBDpjt7MuSEVIqWzYZKWUbvFga0CilZgTsskhjfrUvs7cgRGYgixLG0+0im5P9mpqKcmXegWF7Tcxnao+rZ7uAO1yvL8AHhmzNSMlJgV4vgvGCL+VWc78CcTU8g6GEFuiVpBCTbrT5gtZQGV0Gkz5aTCARy4L6xiO+yMpHFhfZWDKJ8GCBeooLjeM5y,iv:5mIyh/IkXkToy/uF93aP/4w9hGDxf7QppEqn5WK2LBs=,tag:xNhBPFnvSomkvLFGIJbeUQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:SEE4SAWdDYKUJlmgcz91f11Yd1Dl59Sh+grIxhRT/pGdrjd2Fkos5ngFev0HYzUVT6UmudtIVWDtfeHXYezeFaVlQYhnhmfnuMASH+Wvm8Ip89Dio3QnEeE1rNFDoQQyrw8VdD2zLLi/rRTXoxPUqlQBXryiMnrHhb034pu7428763kHCYTaeJD0nAsg/IcrpKzEEo7AmyfRHYSNMjKjXL74Q5I1JSHLjfODitwltQ+F3E8piZlmaAyiHKrKbdnk8F09NRpsGJ3RmOxHfQ==,iv:wHjRKeWTSskkO0rokd0nQuxwPXnhhODxKnLcXUdp+F8=,tag:/pQI3uCPKG6IvDIc1kYUqw==,type:str]
    known_hosts: ENC[AES256_GCM,data:+T4AGG6fFPkMz0TEXTa/eG4kv6ODkaH9rhr7JvPxj7dGkROl54T48awy/aayxhtwtM3ezUjUPc2/SWleEb6QPBGU8Tuy+XjyAypIHxDHkAvasl74mh7Nh0OeqvX+sTP62jD6dEo+6yKiVzEUQtvwDNYPzF77K08ta8whu5a2SlK1K+fZxcVybHeNmx8UBConh8RQYWJbLahFg2T0EEIe4qQBluAXL+GMWh9a,iv:vxj+dDTY0mkdFu7PtE2CGzsF98z25hazDCKxfzuyJT4=,tag:AEpDU8w0hwpS8AD0Qqsbhw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmMzlmNnVyMk1KRzBNY1Er
            ODY0VmJjS2VlM0JVclpuK3hldWhLOE9uUkZ3Cnpyb202RHhEd3lhelU3WUJYZ2tT
            SlcyV1llcVQ5NWFvTSswcHRubzF3aGsKLS0tIFlVTjNzeEFHUHFidHpOQ1J3dUl6
            T1liTFlpclgwVnA5MmlBbXc3aW52YVEKlDxjvgwZBC6A/iDc8amctZiX4yvNQwaG
            EmR5xmHSmvkPpXL1gaVSckJ8U+/faJDLU7Wvqw8orinY/tGW0/eyYQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T17:25:30Z"
    mac: ENC[AES256_GCM,data:BSdZ2mGVInebya9bV4IQLrz4xnNiHqMQQIvEPOTfac82f3bLNLirW+M47o6t9xZhhvi5d/SxRUq/2xl5Fv+lc2FRnCSlYTF23szPCjs8xXIp0RCo8HJYjLR2jrTqYtRq5Ffi8+yRHxzUA9uyTkpKjxQ5V7q4T+j5yzeafQ+rjGg=,iv:MvKd7sOFnrdqItMcHGbMccZvvhjo3bv/iX93ToJFInQ=,tag:lldO/a4eyQsDrrJe1vgIUw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
