apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:Q+hCuMiQzsQR5RnZ0HUUahOge7feejU/5sETZwMpgFXNc7E22tp7/ar21Rg7xE9E0Jzgz8CE977fITdVvUUgzX+rFQgphicVOwoHkIT4KFSHKg9HYRNvXccp00Y20cTWCfWMc9PWLX3DvPa1fIL7YPnE5j7YlVL8l0z3HkvtBNC/7CA48kg18PUyBQn4yratbw9DfCzkt1yXgPMrgv2TyxB0SPRxQ/baRPDAew0ZOWhehW8fqWMy6a/PhxdvGOhpWsMljAkXPwnXFkZ9ZQxyZ4XkBjfSC+hQEjNIcJBe1pvoyQWSfputIBA25hfgOknHHHFF6genbsw4vL/SBXhTXlAIYC5KUqOrx8qD6e+5EQ6/Cz2RANlsTYnM/+HB+Q0w,iv:Cev2QtkJPxZHNhQAwdm0wq/s7XcVHj7qdWR11q/+Vvw=,tag:sXXw61P+U4gpyZUtFVTW/w==,type:str]
    identity.pub: ENC[AES256_GCM,data:eLGRi6ya2CDyOv2s66Wc1R51EhZb8HiaY5mFMVpyzCTStUvjXKJYyxSDhB3Q211ljK1XWjgg1HNPdaqYFhmBbUs/0hZyvPYbLI6cNq2gesQB1Spt9I5eiyzE+E533wnw+XyDqNAN7G+hd+wUQ8genxgMSfNLrx2+ENUTVoehyPsDVaTlNjnTmVTkOETbrOGjNFlbNWmv7RhLSNbxhgGReKJzSuMkDxg2T1Rr1HES4rfG6ieA7S5csedOTEsVgLqwChAN7U7GgC30YDl99g==,iv:SpSwx11iE7cpV5po8fRlty+2YkuEbkh4GFYP3xTsCZo=,tag:PVg+wdAWYK7Yy8m6QK9QYA==,type:str]
    known_hosts: ENC[AES256_GCM,data:go4jIAC+IsQ5RPpa+4H6vTIqsaIkaprf/1pewOoKB1S7Ka0zZxTq/E9TwLth54R5DydZcg4wobdyhoqPtVsIR83tfajvdvGbZb/SMhYQB6HIGPevljW0Pexk+bZaKk3sllplWu62fnIMRqnbCgJRJEZuTlU15RvfkXrgKGfTGTs+5aUe6n+LCX1XoD8orMz+r2cgr4cpkRRN75VzGZ10DI7GeZfXkpbtvOqk,iv:Xs+fUjZEn6JeQNx2Hhss49b/i4PR1dRKbotCCIBC5eo=,tag:/zU2TTgBl3FdRj5RPp9HIg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB6dDQ5QW1xRDE4Rk1hSEJq
            WDFQSmhXMWtRdFJOTS9PdG5mdFNZcm5WaWhrCmVwTDhwTVNpVzZNcllOZjFncFNu
            S2hJV2g2d2JnRFZSNWlVcEVodWJXVzQKLS0tIHR1NGtjTUVJbWRWWG9VZ1BOdXlk
            c0dvdFFCZ1pWdCtUR3BHYkgyRCswbGsKs42P3LKBC2e/Nfj/olOTzO9TZTvf633x
            xO+1nhq+AqyQLxpCVPnGQ6Cwbf/Mp9IsC2/ABPuUGifttTloR+zMuQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T21:37:36Z"
    mac: ENC[AES256_GCM,data:NVoKEHJbtVI4LE+KOv3hhK2NJ8YYMz/Zo4chmycRZuztCEiD1I+Zgs5LXQ3GEda1HeLiN/eiMmJDhJceas3zciIyvvzJvMBiSdvITgtYqO734dvGTK2wg5/omk1Y2iuOXJlUR5tgdRmXm6qCGectQY2TYZXdN3cTBOdYsEO+ZUQ=,iv:H6LhnUvkW052fS49pa1rzmiZVpbSUy5g4NSW/W2CnEk=,tag:v2g1cmNVZwDobobh84whiQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
