apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:9uJ+p5iMkCdpEa0YzhPl5xGeIn57POKfpzOfmJHDLMYMzgtnV454Ydv99tK6LN7Vuya62+zgO7LDnOf6AZnVJZ+FRLwxhbKc9eZU0q2Ky/E0bZZqxJ/0qqlLhwNDGetWdc96QX1LFCSMnO6NAkVvDwEDCXAA8D93SkDNXGtVAikzEizGP0vcSJds2OQZK6s5b7HkR++H6Kxx1f6PzyEJepM7Ohjp/5l/gsh14edfY/TXOM0F670nM8VuvFnshSYNfgbu+ykFPDE2GALB+gfR00B89MxhzmVnupxRClSlyglBLeBBf2i7W7IC9xb9NPQflPB6+fVjYTfk32KDd8E77KoP8mANdxl+xt8HuuIYh0IB2V0MGfkf116bRN3A9ZPe,iv:Ftf66s1rn8nXin7IjU3+/41esz2/gxWygNoOBNaEF48=,tag:78OS5gssxnnYl8jeowpC8g==,type:str]
    identity.pub: ENC[AES256_GCM,data:OU6v+NqXrGDiV4S52DwnwuPkfUY7Ya072aDlaKYzmFEb1Jmk9MAewZ/uoBJMXTl1/ffGveSzweomNGsrbDhAI6T4XffsM2HRj7erQuHB7k6PZ+H58RVev+cF9MQ/hJyGdabtaZ2TkWKMjeWWchihHQFAfU6b8UUmUvaGQduyXEWSGYbjdTDwDDi5FXvwwGGOiw80fj7EzKVbDWEobC+Am9gnOw1BfcLCU5mOVS9KTdAzBTdbpSFkILxzmKcmhWfiiDToNz3SQ8Oc3lIkTQ==,iv:tM+TloJA7DiS0u3EnXOcp1SOYcMgZw3dQxixqi94hbQ=,tag:Vy9/UMFBiJj1Q97QJwOkKA==,type:str]
    known_hosts: ENC[AES256_GCM,data:zZdmqWv7t3EVQ/r3dBJJnXJfIvgNQazs/P/8fcb7ChwBJ96FamvUKLsnfYrDgTwra+FzN0UL4sExU/xEYMA51hwJOoLLbjPzTNuu65rIw0YWK/c724heeT7kdtKdvl/YDSK+Mxkb31P0p0M5XG2rADTU1TVOznH01ZhBLsONkzsf4DvqJCbcLpQ5B/thUCCp3NmfdFN1y6sMpz+qXaVCIgQ1DHMty8yIPnR2,iv:jgLdtHNf5z9bhpDMUq7otQ0eFaQlMx+ultz3ej1OpDw=,tag:iIryGdAed7wtTb8oxbv4Kg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZV1V5TGNGSFZJdEtjNUtz
            emcrVzQ3NDhlRGtsWDY4M28xRFJiZWFOZ1FjCnY1T2tZK29UT1dIZjVjbk0wRDRL
            R0k4MDE1MUVwKzlTM3hiYmo3Z25oS0EKLS0tIEJYNlNUZkRJa2pXNWFVYjlRQkFO
            cGE1Y0ZPSHdEMmVDenRYa09XekVZdjgKOjrz856urkKsT9gTBfzjYCcROmHC/qtL
            fMf1T3iZgoRmAy+ZFFqWPGQBMjq95VCPCCsYgJeoDwobS4g+dfaUGw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-19T20:10:10Z"
    mac: ENC[AES256_GCM,data:pUY20CvQ9tt0QOa5Em21vGX7xyeo2TcRTysfeBo95GNxOUJ1G0ixSPpBjo9MVjKZRWcuWQ1hjMoY9Uqq6lYzwIZMVVcv0vth6xODzwjIpe4g9fPumFxZ30MQbKk6Mj70H3DEFqt7sVBON8nnf8G6qc9hjDFO8t9tuAR9VHF9WRY=,iv:5uMSZDPNxnlymZ7+S43JoJhXCL5dNOLn5hcF0crfhe8=,tag:C+92Zy1VY0tD1xtEjshmlA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
