apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:MuRE1erJSzk0xg1GQLMs4Oci0o0/jTkIgre13Rlf9EktjQuaZ78Sr8AsqFlo9mQmrlt1kTVYU2oRwOZR63mKnAKfWQF0JpFpLqOHx2EDx8joKcfxGC5G7BvMPyigMAifPsfM/aN+9FutbH2n4KBG81McH3ZarrL9QAH6MQUdTYZ3DWH+B25smiilWpghoy1E4VJ5RU0HkFwWKlbdjgPq+JaCX4i24rlVck3N0aBeQvNIAA+G3iZJgO0ZHqnlA5mgJ7EAjLhHd4XS80wrPuJAQ56/0lIVyxGXxnSgFpGByo+TIIzdACMTfucvBC66XSZ7cz4cnzAHSatH002CH+AjniKVgnFExhltafLJE7uRKYyNMHS231da5s8syft5slbF,iv:XAgnt1fh+U1eEso0hsF94hLPI9sQ8SooueTz4vEHXpg=,tag:BTWFVZTqwnWk6tJam9DHmA==,type:str]
    identity.pub: ENC[AES256_GCM,data:dXwA43j0wb0yPvWl2deXiSCicabDdkrfNhXQCxTwAEG0+mxGTC9UERtsgr8X56tMqEhM3wre2UgQJ3yfh+5itAj+2zVNZqM20ltyxoH4iskauWiQrelX2msVvA1gHWobtGTIAWuoDN0s7ZUCRsB4PTDtmApDCrXbFLdFEvjmmnqGu3K13wqr7MgIm3up3Cp8zArNvoxdm2jJgsNCLuGJtNo+zkybe4pX8H7N0Qdvr0/UsPkvVarVQ0Th9s7cxMw+VzrxcywVesYWD3q3+g==,iv:dn/5Ns01ZpxCXr2MxGUMPBG80rFcF6UBCYZlQaRtAEY=,tag:nPCB3/Jff0wL1E0RYp+v3g==,type:str]
    known_hosts: ENC[AES256_GCM,data:7k4u6BAmk5+J7+9U1q7LSOfDvYwcIIhUgKNTVSRYJ1zra5urkbwnZwIixwbFwiSbfX8zWGY4tqDbYQ7EwcctSvqO8FaKcvgITPmUeMp1AuYxstwg9/fp2EErqImkgBE1Vk5dxsoCcBnsKGVCLbZS4/RcwC+MaVjlHzeo0NWD0RdzJ+nDJ7/5xHPAYHV8uuNjpy9t58r1p6T0r1+3MrMslLhcdQMrQEfjKD7h,iv:Byg7fzpKZyzTFXayQrp2pzJRTvHVmpbvxLBvGCBObsc=,tag:nk3C1aYHQ0/cXamey/olMQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBHMlprckRjVDd6ZlplSjdX
            VnN6VXc2VHJxeTBnL1l4c0EwTnRIajhTVlNjCmpXS3BqREVoWjZjQS9HdU02N05m
            bFFHMFJhazNna0hJeWxpRkZ3bnhmNEkKLS0tIGFhT2VmS0l3eUltNVFyK3BLSEIw
            NXBwS2pQUGVBRUU1MzZPMTlxSUdSemcKB1RVOlPUtmm5D8kzojw3GcA3vnhgzbDM
            9FpgNu93i/szYAGWJayXeI4Txt9CcQMJHXrqbevbLYpfghCEG8DSNA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-14T17:31:36Z"
    mac: ENC[AES256_GCM,data:HPF6HZ0KzkmnDgTkUVCfbaqpBwQCSZcGqRjiu3UMMT6Cj5I7iTsx9fqvvpbeeE4u9/skfX6NbuvZeTFNPi9+CMnZSX0VdpDcENY+qJ+SILzOwcO2LfGtLwPJ/C8qFm64xIixZaj05cXZUqddnmEFOTtiEKNPwyL0dgOn/rPTe3U=,iv:9uQz2HHhvRBEH1kwLFpssOQEcgH5nXrkuf53FWFntNY=,tag:gZ9lpr9byC3SCvPeGuZLAg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
