apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:ucMU64YmUzODulQ9PkO6Vo3c3OqrDSyKhduHFujM+LGvex5Co0TEefvfLG+PP+/Hc4/wwUdK7++8HZ7c6avTW5rtueFd0k5iKXYJvSNR8FGkAcmnedBML6p+bdxKXSB0UB/zu9MzR+U45Q76IqyCKZqlHZFK3gNDRrZkGl6xwGu9mrWdy0X11jxcPCuolZW4nk7CKETuepyWKo/QoUTRsYhdWHUHENwDoU8QeJvY4SJgNQHV9j+OndZTXnNBOEJ0fREY/RBWUjizLdnTqUjdWDFs8X8FBTK3y7Nn1j4jNUeASD0E+pXciaoPQu6xcilzw1dk+Pk++0pCUQdidZiYtAa/ImXkvkSPf3i8OGon39O/wPykzKFZ5pYu2ilYQrTj,iv:37vyC5AkKtQvFFUXVOGxL6h3meFFsnF8JqLLD6aMoEE=,tag:Y24W6taSA6ha+K91xwy/uw==,type:str]
    identity.pub: ENC[AES256_GCM,data:ql8S4MUd1pPdVPSxT16bhRxtHzS3uxXrgSwKEfcOvK6SIrlbwi9h2KRc0XyNOiYhJzHKhdeCmleSddorQwjws7j66/wUbBe9p1CGqESiMfeAOVw/h8zCQMN2dhLP525JOdTNacN32SD2U5YEBEbaOG6Z9xa0brEja101VSwPcS5RmnvlFHLs5vLbw6tLp14IYyrWs5GWN7kJzdOn/CHMwc9FCKbPWsXl50LTnnHAMk7CC5n1n6nevFIPA0xNwwZrbQs5J+MQFv9Jd4kk3w==,iv:eQRIBxgQQud/laz8EgH0euQXo0jiQm2Mav7BTNCwTgQ=,tag:E3PRtAvNxNYGUQnNzkbPqg==,type:str]
    known_hosts: ENC[AES256_GCM,data:SEl2+k0fYRBhD868QarElwe6RLt/mc8391zYdWcFky18DFB6C4dtdLLwyqDbFzIhhQ5gNrj/+bQ4XIP9nmhtB1uCXLlJNFER6XInLTkG1KELW4ttZLgD7UUsjohwFF0e0srsUMfzzowGPLegh4Lak/Iv629X1GKFrgLePjBSuS5B5D66PEm2SA4xs3GoigdkRcRR+bYw8ETCmOVp/ueu65alZNjtxiHkxy7b,iv:ZMU/08DENw1Ew34nvnN4o2JUTaJ4zfq4gjqu9RvZefg=,tag:N4muko3Opb6W80+kZTI5hA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBia2x3bHk0Q1NBVlBCTGx2
            UHJ0SnhNWTBPUjB5VHFxdGk4YWljWVRDMTFRCjVqSDhDc3htZWRHU2JWYXJLOWhJ
            VC9WSHNLbmZkS2w3OHVMWUdlc2hrNm8KLS0tIHhxaXFWOEQwWUk3a0NiMzZ3QWdX
            M2t2bHQra3RQb0hhVUtxbU0rampVejAKaj+/elbkslSULG4PljX77tiFBurmaLjY
            rlO7TOXUcDJTeyWGjbLYUcKA/+cACKqzM/se89bq5WN1/q6VQDF6bA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T21:57:43Z"
    mac: ENC[AES256_GCM,data:17EvQII7K7Ir2kHu7Kja6Yh46wxIhL/DfLWLp9QZELoswJrZCDn3k3Sr4wA0CUxuEf0A2JNVZEicOldVQh1/PofALtlw0raXaqZe/tq+eotD4aHD6IfI8+kGxBrFI65M83WtFoXxaNZWFqPrF8fFodUzgBNUSke8t8oTlYzeKRM=,iv:pGIS1285O/CiCH6wNaCnVnILyR31bl10D1Nkla6B9T8=,tag:o+7tnYdrpDfquBVaCNglUg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
