apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:1kfnp01dtLej1r2wAk3EL8LAxj1emBMHDH7nvFTUS+kA4TytITzIJFace1pYcvQ4HqAOwJJNr5Wef0S1g2Kh6Uuzg6sGtW6lXutVWwV70wpro32yC0FdpFvt/2CkT0Hxx55gtT/v7LJAnVJp/3WwcBhbW3HP1mh+nHpfkD2mHrDUcR+89d9EPSLjmRZ4PUsvi2w23dfoiNR3i19BVQTgiGFyeHch9HnFahizYvRmotvAhZscI1YVcEI/JQJ4H/+5PKgiCJTdgd4E/ar8M0RBcxQrG8aYxu2U5U632OL1+lvcil+pP7CzRy9YTgIFWTIYEP2TsZXZ/T+ifm4SKT4t67tushP//T1mkoIUWTWcMAznGsuGqxP6EwonpVuUL/bM,iv:ySfJCtV1DvG1IqMcQ0ovxUXljon6WP56ql7KX7hBcQA=,tag:7UbblM4p3/2+g96sUqvKAw==,type:str]
    identity.pub: ENC[AES256_GCM,data:61g5pvpFTcP6orSEd4holS1kq91smGVEVkag8NUcL/Di9FgVEX1Dv/XY9ueh8LwscnM9GputwF/wJVubhN3pZmLsHCWbFVF/rWfREwYeiGuIoBx9npU65RuTgVjD0xjOY3YP60WTQrz6DRqjcPmILBTP7fyEStm1g3bBr9hk+iLx6xuvlwJ2ENopLiiPCRLzQf7iimjPC0seZlPgc1dNJnxfB91vO5xeKJ8hDRx4l8PG+5pretH+vstv6UUbeVOyATLCMfcTpLa7rQgkDg==,iv:SGoohtMl1Lo4G2o56Iuid0LmFWIaxSviFc5MToE4v9E=,tag:21Dv14zkDreLDoS0WtF66g==,type:str]
    known_hosts: ENC[AES256_GCM,data:IYJhioYlOXDzzDvOr180BV51opsP2Vc8ZzVY12hulF2O8EEXSuT9LEiIwv9biwEFVgGIQhWCUggA5vFQNKIwO4IxmTxucYiWGoitZRLDI60JsgMDHez45yR+bXp/slGuZ6yrmFkStw0GyLDXkc7RJJItPNkGWBtbCF/I2iDf2NXRN4aX7QdhzJ5kgdGqYv7mCu00d1RHD2gXTFxK750xN5DuzrNSiMRD0fP/,iv:6CzyovtmRG/jdMD0yEAxkld9xYRc1d6RxVIzRxPrLPs=,tag:/D3iFT2DNA8yJLgiF9Ofbg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGM2lyNUlBRkpLN2Y2NkI2
            andqa1loT2I4d0NMdms3U1BsVVFOdmVielZzCnFsL01RNlZaNE5DNW53L05MUk9w
            a2RSaWZTY0FiSFJMcmFoV240Ym14cHMKLS0tIFRXZ2RvbzVaWG1UdWUyamgvUzVh
            TWxHZmYvbGtxUVNhVnB3ekduUnI0dWsK2Wf3PealdakXlYRHcVBt4wqhjM0uDhmb
            HMxOSE3AGifoKX/e6Jpz4IoX4zGcji8Upj0GT4sXCXMMLeYq9nNEYw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-27T01:19:13Z"
    mac: ENC[AES256_GCM,data:pa+3OIt0MM4Mj5Jgvh7gX4TUUJ/yJwKvhOZpN9D1X4sYBLuHiKJIVuPAxYhGwXqYZoD3LrWibV533CGfErYOvh31nsVHtiRKXrZVgpjhAze8tIpQ9/mSvrIwKOmIW8r+ZUgo4pewKMArifaewC9Fx1rYqV7Qhbozt9A9Mctudmo=,iv:Xj+buG/IVrrnulsButmNvujlgbVYoBgQtlqtVgiL6Ws=,tag:0+JKV63SrhiXnehrgiDvLA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
