apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:wgci/VFxYFmBL4rgCzHNQnE/zT5S2EBS0NMQMypxqu4lcYfgoWxV1llbiWfRjwBjjRpHZgsnK34VmAwYolsSKBVT4X3L8BoerFZ+uDVoEbhbL9z49V12dDGxdkc0np7ThRNagaPu13B2uDyQs2Mhe7MlzxliKMyfOQSVjGUu9amDQZiJcd4odlPw2DhGqG+MKbQBiJCjRytQXGK/ETL05uUIvHS1/P/67fTETrhLdAx+gcoh6de8QWQ+SHtg77crbsWKR+/FM1ClClCeV3+5H6NEd5PuXR65GPXwwFS+nOF4A5OMAMfOU7P9bXk/NeURCnvaiQkqxBf1eck/mr9xhcekdo+e8mzeWBeSHY80s4TbJmL8h4WUyDtPwxcTn0zE,iv:juY3tgV7drAioRI5H4e+wBrXy7XvnDBSoiuX8aXiSjE=,tag:SDJo1KD1bJXWxhWkV8armQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:c5gL2e+gfg2n2ZPqYXBeOISKO6r8RGva7HmsEq1F/Tj8HJfv5CxvOsjDR779cByoUw+aRQ+Qi8tf/HqL4OAzdE6G7GT/5Vcb7vIoz/6mti2aBZCaFF7CFvqeWeEXd+L7KFKy1HpnPduieroyxXRDxHM+1PZNzYfvX43pv+8tjxj0aTD2YcNxImw+rc5vSXJAuJ8avQ1huPfnAcWzuNfw1G/M3wZH9ZgNeN/B/x5TVEs/CvDgSty8LKPVm5IBVij0gEDRDEX0qVOK4/Crjw==,iv:X2qdv1GRhbwsufEs44SiglHIvJVvf8TFYCUQRDqLPp8=,tag:BSqB20GojhlD+EKElN7myQ==,type:str]
    known_hosts: ENC[AES256_GCM,data:aeb3O2sjOGCvrO5mDRpKo5YnLQBMfXyV6OukeeepdQ5NjHNuIk6xweh1YXT0v2LNz8OYsG7qZweYIHA2t5cUWK8qizlwxbGvGk9W4Hb0aHZg70w+x4Q6XWUc0+YvSF5R7/t3EjpgSdXMQFQRsUOAFigm9SuGtVXGOZvcOPD/bqgNIFz9ojSkzqU+MNRXGXb56pERP6BWxcUfFI1RbS2a/LRdw/8LoqcOeqmV,iv:t7iynLvaOOGMhYAftWDNeCxDraM47qyUVQCWj/0dkq0=,tag:KRe4MtGRArgpwth4kNvccQ==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVZVUyUzNSTDR3TGxQQ2ps
            UnN6RjhOVGlGWkd0TnZVUHRvWWU2K0xucFFFCjRyQWJ3TXl1Ymx3eFhubU0zaWRL
            OUF0ZHUxZDZFRmIwaWN3UzhsRVhlT0EKLS0tIGFBblRWQ0pPY0xONzBHWjFMclh0
            V3B3WWV5a0dxNWdJWHFiUDRwTXM2dlkKVCXx5PYNz7p3noOOy9PkZJtczyDsmus1
            oj9f8ksz5ZF3UpGLA7NiSVqp+WfUe9+KwK3BXGSErrWCYpBXFIRQxQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T14:48:21Z"
    mac: ENC[AES256_GCM,data:Bk+mADtwzSI5A7dFfpav5BLHqnijgJVjveS4J/BO683BC+uVAsIIZjlIuD8hlKlZO0J80bFI3TjpOs0/BT4KHtT9PEjlR+Ftnc1I0Jzl13JQxv7Q3WFN862w0AZ8RIiA0i+zR+4ZngDuUlr2Pt/DjXfPRR+ZSQwTqxJc5XafAH8=,iv:5kcosfdBFV60j7DPGTk3FyZ7b46jk7Kd/FMLm+8+38s=,tag:GVRK3FUUTurEEenmUX6IYA==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
