apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:dNhWEQv7QQoeHO4qvf0MtcwiyXb5s/nHrbCJ/qwFuy6I0umj/Pk5SKeYbv+oMIVP2+pgj4kWVlq5cgEZnNG74sv02i4hbjdTot5z4TcW3MgzLXiSHZ6eZWmTRp62KdfYYT3Tit50DATUoP2GfBat5ZQ8zlcOvW1tDfcebd1km9mx9bJ1/99tvYOzJOMoBnnbAgTXpBJmdXexUmYRwaQlASRKapAN97bGYOnVpczzN8+K8C7KhFXUBDz9bQK4uHswGVO6e07Nc0oDQbtKvA8eWcdZqQ+Y6IAqk9AD+ugG/6X1ih7MCWYOFc1ulFlBZ1bxtmxZib0UGsCQo/v1J0Ex+WbmLhF8chn2lVcg9J0f3lUPeGJhAvwiHfYlDO6bVXRw,iv:+q7Aw47+efzOfWheXDbaAd05n1cnXla4cRE5tUcAu8k=,tag:hZItLo0lpnKBdmHOPpQM8A==,type:str]
    identity.pub: ENC[AES256_GCM,data:Z2+I+LCSaAyLn2WeZd+NZSEhYOMftlXQmVc2w3fJ/sJ1PLaxZU9z2ZcP8YtkPKlQ77QyvixKMdYvGH+9JQJNLg1phbZHNHn7ZRl7AeINfwPIrcnZHOslaatY50wTJ8Og2ISSY3TiLNEtHfg+VTXdEFF+se5kYeAV2QUCeoDJFX+AR986R4iviGgHym0M8sAucD0pDtnmIffYkFbUKh40J5JFY/xcfonWkWozrljiFZLRq5jczNeFjxIVbS4u9ZwHPzoMmTmX32/ATvKs4A==,iv:pBXAcrMnqtY+iqM88EScTu+Jxe411OAzyldmoftPm0U=,tag:IHBnnU4sqqmE8rafG2nsEg==,type:str]
    known_hosts: ENC[AES256_GCM,data:4OBOP3nkvYo0l4V/3YiFK40M2wAZY7/IdDUzQFhsQbjLBuWIFsIOYVkhfJyreN3tRTPj1HFNheZ1rmZz/2eJf+xfiPk3wUwf0t1sD9U1qYmwnptwLga2WCK4ggLewPJ0osJ74juzb0oyZ19lxX5Xp9EZgnDBOvy17IBpji01Qhsc5QRXKHpcu4B5xOWSICD1SW82KqR+Rc8GJ0hpH4X5oVO/MaZeLpLPV4DO,iv:L9MMl8I3M+03wegjYlkyzoo5gB1uucopKkzBMhjKU5Q=,tag:ZCrUEWABb/qp+HMYaP4anw==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB2YW41czN3eDlmaTc3QjNk
            UU5za0d1REFMMFN2SzMyREFJZTM5SG9HTVVFCkh1MnVpQ2U5cHZhOHZLWkRGTmFL
            ZEo4Nzl4QVJBUkhtYStaWjRvcmdSekUKLS0tIFN4RU1oc3RVVWNpb1hsVVRSMVJn
            QnB1NThzSEFIdnV4YzlHOWJTUzJvWUUKgXduxDtjYt/6WAk2FzZUGiE2OAlwpSRJ
            FXdzg3gBVpTNbMb9GZUTfSmIcblte6uqR69ZffZI8D7H7C9cWxTtzA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:06:55Z"
    mac: ENC[AES256_GCM,data:YaCB+y2j7tMKYk3T/gZjywW2OUMGQEuQfZ4EowYlWBhUwsmXvaMMdVHW/BFxZmzXD9RZPzjr8oIDf9nw62kslJ2yHqYuvRxOCE5e7r8mX/8mn3A1PdWJwZx1s5wfFqWhgBcUAQkd3IQcWmPWKZ7Vcpm419D0bNZtDwmASNdOC2A=,iv:Q82KJCASyfcw6ILagraj7WJw+mrRYlnrqhZrQnTNsIM=,tag:aKOxbHwBpMMjjf1nKHKU2A==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
