apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:G0/Wu+NKkh0pCWsWYFamjNEhHKbHHRAE0TyjIpVJ148OsSvADjagQff3Yas/a/5VJJpU4Jv+H6RHFXktpizdgyo3+b4BCPr3sjy0k8vWyLu2sPHzenSrV1iCXyID/7O3IwsnwoCrHCni6lFdN/w2Y4yiEzw6p9eBl/GMGcaTbHbervfINecaYlZPezSaMKBpSWftJ7t4z9VFwIxFolzP5cmgV+55BG/7uUpGHs80jtMmP6qoQHe9OSmOTGLxuK89Cb69ZXQ4LPf48aLm2mY94kOSfD2Ev3hmSmhALwcRnmqrHn4+9Ba+POc4cRMECOJaez6J+yPiFXYeCFK+UMxq6Tk2jTxrRgvbTBHi5UpyELw6zocMN9sROq27/BYPQO2S,iv:gZEhpnighFRNYoGcDDPG4buwFhMFIPuuIOUo2285msY=,tag:47m5Kah64e2keUi9jHk2zQ==,type:str]
    identity.pub: ENC[AES256_GCM,data:MwjcGQt7Lw5/eX2Hpq+yNPOidbOhplG53eAeRpXCN7CRSC8B3oy0YfWNFAPxEWAL/kOkH1hqDbX5ICtDqlYhJIwMgO5vhq0nGvVkxTiB40kcGnOY5bLSUy8OdfLZ8HpV2FsGHp3SAOka0UhJnSJgkJAFGnuf+bSrBdzKLKDcsaLsot5yvz/xz9bCNkyKaAfwcOG44PVfkFJeF2uoV/GUztLFdeHgGaR6fb8MMMIODUGs3Dp9uazosb97kRYDert4v8kDkQfybUk/Lm9KAA==,iv:wppwrL+rTxu7mL0LKm2QZSQsEdKh8ZzZ6ddM3DoWOlM=,tag:Napea0jbV7GcFtneTXj8Lw==,type:str]
    known_hosts: ENC[AES256_GCM,data:fbk0dUQkX6dLD7IhJU0NADg7CpnxMoN3o+qpxPMZ6XRsvtzyrrWsy+gNg3Z19ifFa/O+DIQbxr7sH9VZ8BsLJjDCv0JCSpG5OXKcH7PriaYUu07mrpiYSMNv0ECubWO21pOULS057IluC/+81fbPvoMiRvubthGrjxwMkPkvKiWQeCIqcQZJHMI0QYhzDRSVry3pZAyRXPDNk/xdTP7PEaXTeoGwJqEYVyKW,iv:i0bro8ew8yzAh/dfox0LkBjlz0tTR7vFF08uaySjx8c=,tag:+x5+u9TUQGNuGqxJ3B7FDg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBRRG56QkpXdXZYZmtnOXM0
            YWxVMVBYcVorS0RNR0xDTUZmb2xIcHJENmpNClNWR09xTlU2REFyTEc2ZHJNeVM2
            ZVVFc3Avdjg5VEVIQ0dHTGdNQ3Q0aTAKLS0tIFpRekI2OXhFcmJyL1lhRTkycmdC
            ZlRYVW9PRXdKaTI0QUM3ajFoSGwrbEEK5tVSN9IY0b9o7Z5gHwDoeW8K/tZWQtbi
            e3CIlNhYOuNx9oVgSDEPLlrzVFE3HpoNtheU8+QiC4uhY+vxh5i98w==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:21:28Z"
    mac: ENC[AES256_GCM,data:DQYUD/SugDU+n3MX/OOeonBMQDBzdwf1eCdK6z1C/j+y7ilCoKc00eELqEGeorRDN3UmWO2nlz9j/RG2PIq97irxQ88HMq6P5V2OfjUHbCCOMuPEhQ5SU+akkxD2aWh92HnrzAicrk811IsjHwyBtZxCpwxOH7pwIzSJkvWe6Es=,iv:IGYNF47Ke1wEHGOuN3wOnBWciSujK2vZ9rNpBMyBVpY=,tag:RQhJUhhR0xJ5xtlJoZ7KJQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
