apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:gkryIApNkJtVqG+qhTkap7Rrzhqo+cg0ydbk+pQ3WRliu178q/n9Wc1Tdd6NgcaeDUHCJSW8SyvTWxsSBFDCehegCLV4/KGnm0MqmFDyqCV5PHPMixBo24XBBJ9J7/o1yaHBKWeND/gBblInv0DiKNAGLD7+jhmI8RqHD/z018FZJ6kv4ZkjrrTNxss1OQ3yJXYphbiYyWcNgeK3283Ka9ciQafKix7H6WTPgXmUv4zY7Cx43OoPecZsBwS+ZzdJo66mxHtJ2oBAdo6aM7ehJEneaPjXtZ5MSBujxWMV3ysijrv4VjUI6M3daoVoXPUv66BMe/Kz0qSdCJyBi3Sxa6lgutbIuuXoWZRZhwMVvLTLcJVftKcRUwRvamywtnu+,iv:s4FP/yDGk/duEieayLvUZwwx16fD7SAgF+RIqzL0z5Q=,tag:BNIcJQWllGqGv/WMM0CbNA==,type:str]
    identity.pub: ENC[AES256_GCM,data:NZsnO06HsF7s/pQ0pMEq3gWn7EByCntUkO1PJsJ+Dmp3MmWDFIO2cHrCcG/Qfl3oCO0SGP1fV3ICCf9bf1XaXKtdo2UwVIbTSu9gTBO5doSjGmItwCpqgLnrHLJYs+Y8RtWVKmZ9/5SR0npPSAvZk5eGIByTXErxPUVFbIBHC4/HNDWm5CYXDoOZhILUcPtjxp5Li7k99uolWgtXy8UsFxL8SKVq4JDBm24Gpw5leIrZsuSIJKNyNCMkhVehrNT0BVbeoMMBmUk2475acg==,iv:D6MgcZvd1wsZpZCR6zhegn3uxxi8EoGd9lFjwBdjdvc=,tag:8wYtbBuDWzVRKMuXQ88PIg==,type:str]
    known_hosts: ENC[AES256_GCM,data:8z450IA3gV68pJzXeMyvTfC1O/ZTCkDfqDvPNtJOKechJzS892P9VvjJ9O2VlitF6Qiv2B9+S7J1Nl+n8xw4OOrNR1fIFdTDj5qRUZ6DaU8sWe7gd4YgW0FQZglB2FJx34wFMqOwF5z0Wq/rKceiaiIkSjwiTxYYQSzZc76xUPwQ6pQ6NhJAlWhAFTj9FD4vVIrzpcPdwqaTXIyh5RDEk9aRIBBQK4UJAOEg,iv:zf+j/1IHZ9nEvlugmSN71H5Voj2D3sLookZhEBGXNRU=,tag:W2l5jvJraYi0f+8IGbwo7w==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBReVozQkg5WE9JVVNzNWky
            STBMYVJDWVBzU2EwODlKb2g4dVl3RGVWNDM4ClhleGN5RVdRS280VENzSXRJaFR4
            VW0xVmNIRzZ5TjJMUC9mTGQ5ckNMY1UKLS0tIGpLTGR3elI3UFRRSXVDZG84TWYv
            NXdOQWxneUtOSlB2V2FSdDQ5SzZDN3cKTX+OJTpOY3bUVpvYJXMVVNiaJYsVg/vG
            CZcsHyS8KOqFpRsbS98jBb3LamF3ySubGaCwLBsVkxP78dX2WM2S8g==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T01:04:06Z"
    mac: ENC[AES256_GCM,data:nPwsSBif9Nn6HWd4X09m64Flln9H4WtQ7vTyPacceYQw0l+Wl/qRw/k2ZsGn36el52qmMQ55YAqGD4nQOK99LR6DfvDt+dnk/f4S4SAwwIbBUhgrcUlLymOnDmG26eJLg3bm8d6TprkGzTHf7qSeHIcja4HG3lq6N6DLfp5zEmM=,iv:GgsTWyLpK1z0DEPp/wrgBbigmTxEWV2vg6PvmQTQ/B8=,tag:z6azVqeFLb5TpGRxvFK1mQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
