apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:te1dHlUPLfVy88bJIE1H5K5wKdrkBawt4rMJ2thUM8p4J6z8d7gkzxffgtHEYLCTRiAKYhxPG8liovkjI4vayhzJNE6/y2ajBkdijBWSelWF7kk9zhiRLDLRSkUQM3ktDD5/hFnCHjcELORYcT2d4mFdySI9daqH48li1xXEnfOSBsUeH/UEvASnIjTTNoHltqHLLabETZW1GGSmWCt4f7d7qNfctzFIGsblrVAVU+PNYi0imlrDDIif0AlhB+1jAspBP9Ln5n6BmosMdSZ/BYvTOuNw7DWe7iqXVhYcNobOsZn263RueEZMJ8qvb4KqXhDSt6ATYcbbU87Djv12OtfvM3cA2wpCGqOpJgN1ncTe4PZaNMZxwAI1kb+Zeuyw,iv:TtYuJN9DkLZUWQcifDBZVk/NfGtv5VnT6z051jiK8L8=,tag:JcuA5FOa6WZxZStfI0wQSg==,type:str]
    identity.pub: ENC[AES256_GCM,data:hPvYAxuWzfTID1Rgcu1X/Nfm4RhG4WO0JqWM+uyCx6l67qbXcq8VqsR7GFib/1v22v9Zh0b2KJXh0eMavE8NdhsMjk3RLklYSMCmR116/e7jeFViUsK4l277bTP7Ve2NT664JzT+sbO2wq65plQDxR7ytjkcelutx1IdiAAAdvYIpo2o1kbP2Sn8h7KlDZpgB1hrlYQzxpR6ZveZCdoihAaJbq5eN97Y4WGcDeT1e7+E3D61YbaLvtYKzmTvgp355vDeRZCXWeNPOtPnsA==,iv:4Ssw73GVG+VkOnJgMKigB1UBWpbkQSpvdv29JdQpJtA=,tag:FgbyWVKecz73HJhEAYsQ7g==,type:str]
    known_hosts: ENC[AES256_GCM,data:mDMo9v12RglaRaIRH/knxqdH0FYuwMRZPB/svCtb4sQWwdOcMuxvrId2hiutovghUIPNYv4Jj4trRQHjhGK2fmIB4a2RfwXjuOHlsIPZl4mm3sqT13Hiw6/PZ3FSr5FOKmEe08y0HV5rNdRvVyKFy9YSsLu3Ju3Y1aRqHrpSnUWZtq8rqGWL9EAa6rRhKXHOPGm7l2rxU6uEXHfCUTJ+C+tgZl2b7UxEoEn5,iv:9+qliU+GsBhX3UzSqUBe4fuobr13vL/J8SFyim8MSYY=,tag:V0Sqa6sDQkbIEEQg6X8f2g==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBuL1RmSUVDNGhhRmk3UGd3
            TzZzeXJ6NjVwaVVDM2hmRDNBdHg2ZWVWalRrCkFuSzZ5Tk5Bc0tBMmdGN2V4ZlBo
            eDRMUlZ4eDJ3dzYzR3E0cWdBQi90RjAKLS0tIGc3K2t2YmJXdGpualhrQzFDT1RH
            RWRDQTU5eEREbWlqOGFCZCtrbTNBdDQKRVipdkqpBmIwCktFBUnLim+YUHmox064
            IBqYlDmFq9bluMTXD7CFGCEYUFKuQu2QwenMN2IK97UGONFY2yZPLw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-25T15:47:56Z"
    mac: ENC[AES256_GCM,data:fMzERWbOVQgB9XGfH4+dZoNteeuiRRKdoRtUhnwROPPCiYUv/tgWNCfjmCMsfYiqF5dIpJN6mwn3S7vr5HKyqwjt9PAG76IzYcMUpq4br1BOkvsgOXgjvsvFJSmGNRwjitei1WqfcBBXEiW2uAd5I6rpsBPcB38BlDWHHV7wIQw=,iv:ojGH+Y5JMeBFa3LQm/PLGURWimm4DKytdwb6NYRt0Vw=,tag:SYTon3Dk9xPUAtjCsc64uw==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
