apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:AndOmioWyO6utAhgfyp/ABWGoU+ncOYi+1E7yrNzGQ0Qk9PVn+YmrTAFeNRLomLs6YMY4u6vpmmpzwZhMcgh9VUM4T9WYOMuFDgMDs1KUIWgqZRm8joHGpa9KlelLpyqECaqt5n2OV46thoBwVZqBZmzMomWQQ89blONt3WIKRVibsHbgutU3VzHhvsNDFw7HQeLDLQTbh2eLFri7o7WT0F4DqaglJOWXdc0fTzlXB3epnfMUkDAD1ftlMtHI/BNgvpoJgr8l/7a3rA+UJM7pxP9tUAElZRneSf8SsDiR1WhgU8a3Dxs9dJoIhmqqDO6czvAxqi+yZrdEX9XFKz0DJ8xZ3UbH0xnlMo2A4pz2QYhcUXNrJ6rfoSHshwPlp+u,iv:vQza+mlCqjNmOYEt8XwuNzqYs5UwpezDWSLyRQ55sQ0=,tag:0eG/aCB2TfZtJqX6pm7mdw==,type:str]
    identity.pub: ENC[AES256_GCM,data:HD7jfmoV74oIUqL1JN7MSrK5zRyPR3J1Qw5ic025GRIG53ztAepsWwqpQWQEGOsy+QVbeE/Gbv+H0SOSBvaK1VGMbZL+Ui5md+gy1Gg4cb1wk3k7ZIMFAFvL91k8WzUuRl9h8t43m3Hbd6yPLZ+vo6kqsOyVsmX5NZwlKdMLxtOF+0v+Da83J8Wzr9jYXUmLxcWBVyoehCRdJuf40CTdNeBqvGzDWlGo+FINSlX/srzynO2djyj87ucj+aLcK8dVzoYTFEMMTNx97z+7zA==,iv:2X8SyYSokImb1KXDe3pIuqhWXiH4JpalK+tEX9PpkhM=,tag:OQU4KwzgWMThxwXvsrns5A==,type:str]
    known_hosts: ENC[AES256_GCM,data:UQY8ikb/xMU++zrP5TwkMyQmbpxJXFF/v7/grgJADGLvCBtFqHpnCh6g1+1gZ6UEn6NIyMQStDYBF4T6ojmNl4g+Hq0BAVg/nW8v6wW9coezas0JT32UmiS/Gv++Wb9JZhFQPS7T3UPZQHqQK+BeVyIFTaO9ckbwewo4h3NXXPElRSvah73MoW9/sP1KKX3/Nf0dSADxF9yryA82DWUVGDc/KGD5L64h8u41,iv:fCIdHX0DtkgbG+cXvgReGwyCcbswx2glztS6b6oURCk=,tag:j2HzIuS5DbmXr6G15rNiGA==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBtaDlndVVUdmdWTHFmZjM0
            c0dJNlFCcGNZM0d1MHQ3byswRm9JRDZWMm13CmR1UDZlSGsrVTVGZEt5UDRmZHlJ
            Vm42MDAzNkM3QnBoZnRKUmhZdktId2cKLS0tIHNRSTgwLy9uRWFWeGtYYVoxcnd6
            a3QxdHN3Z1RBZ2dXV2w1R0R3VGoraWcKLfAL3T+Y7brguKwh9f6NdzepsksdxZR1
            nHFnpPtofF/XPmDyLUe7TY5Oh5G/0WWNoyA53El73Yf1bx1JM++srw==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-23T00:27:42Z"
    mac: ENC[AES256_GCM,data:GMJ50VC1U4J5VXFsvwebURJmrC7WkDbOXZ3fmTy7eUfIOvLg0Y4Y+a2FMFMVgpeEoT1Gv8gXt9cDupG0niy1kkDdeRs/QipByMakGYDCD2FQh7xS0iGap/VYamRJQsVaD4SqP/pU+MdPa8ZddzA4gqNbng/tl18APa41QfWv0ww=,iv:qiwOdb16tUx47ingb0YTrE7L9m1gkqlK5BIsXt8p9tw=,tag:eRzXTUaAOsi/Xeeom1bfOg==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
