apiVersion: v1
kind: Secret
metadata:
    name: deploy-key
    namespace: flux-system
stringData:
    identity: ENC[AES256_GCM,data:vvMcshMfs7DIqNbjmBnSohb8T7RLFaFDWyPQBIlEzq+X0Q95FU//7ks3soDB0W9LyMzoeHJD1+E8F5BmsSczQo0QVq5PlMHwE6cRJseAkYYqhqR3DfpNG79Yo2yO4X/Fha1tCvZV8MiweqDpF1nCW5hk1ZK0JX0sieimLeAXvcLRk7FR8rWQp1tRYDM0WJVDVBH/xbukczR7Y6Ci6vzwbTOzV7ZWcBGLIvyTc/Q5nC7rsTruLjo+sNPzHs+k/9IYUO/hTcLPZOhle34n1iwPQ+Ib4y/ErWdefOYuoQ+r9xJ8sWvAIjTQPyghQfTK0FVSLj5LFNi8OcdEa5F9e4Pjc7RJ1FJxH66rRaN7L5ndbIaS2ZHJyoV81NfKwfIobfvN,iv:PuazicZ7tknYzE81EwkzTGOZ6vcPqn4YjetNtUaVHMY=,tag:lBRdkYBFcsSWtAKrL1wlaw==,type:str]
    identity.pub: ENC[AES256_GCM,data:7i1mG1ypf/kb9tRRfMQG2hsBZh6RzuH+02Vrnk0PmD6QifvHXPgeGDUAdjeRJ6zY4YcRMwgZcjrNkHlhePzwC+jIF5VKWJCG30RnR9PzDpSdK/YPhd1m1HKlA59okA5hI0ht0aWZ6RgKe8JfL6dP9RiR4tsI1AwhxDYY+bKIHnnb/irnrX78I87BwhCJBQxbdbKRylDM4KWEpXtBpB4R6cROFwL+XDjPiwMg6AzuKHDSKt+WONn7TNzFdGeUesLKMWnKdzXDJnjhFbrfkQ==,iv:LH3+pknkUt1n7Y1alQrHG//YFIJ1+kYyaA6wmdOlsN4=,tag:IippVQtMoT6Gpio+iI5l0w==,type:str]
    known_hosts: ENC[AES256_GCM,data:eov+SomStRZnwo5vpP19A1Hx/bdCA6VCOay4NG+T7z6WWrU0azpq/t3VBknzRF+jkYhFGvmbdMOogOSEqpaVb98K/BSOim2tP0T3r3B+zlxx1kZJ3vSEhs70vLoVvvspfY6HmjtvjQ8yfBUSox1qncbYK5g8oe4xUip5wSXEFqGwLggusmTleWna+cSXMum2TLdthlkE6KCjxBKYnCc1i+4gddfCiJLZ9dnN,iv:MM2VEzyo+VXRSgwP530W1eqNUTpEpzVyX+ajYH/KcLA=,tag:9Rd2RqBiVf85c0Lke9oFQg==,type:str]
type: Opaque
sops:
    shamir_threshold: 3
    age:
        - recipient: age19vztv2t0zruajlwwp8lcmle6lp8mmtkdvmq28wug7c66qg7ghvsq9jv7js
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3d3BZdDIvZkZiY0EyYTA4
            VGY0VlAreDNRZWtVNFMxM3h3MXl1VnpPZW1ZCnNMMEd0OExJZXd2bmh1WFpCbHNM
            bWpUaUFqNWN0WkFTWFJjV093bGFKMFkKLS0tIGZVanVsQzUrT2RIWDY3MUI1b0Qw
            Q2VDTEx3dlpQK0RGVFdEZjNsTFRkeVEKzIKULk6OtisAkU8r5/uXRzA0P4nrnfbm
            QzG1wxhNtPjVlVpSMzV2mZ+pyg1cdqlf3/PM+xFOUZ4b1w71wbH9ow==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-11-22T17:36:35Z"
    mac: ENC[AES256_GCM,data:DgsIX/k7KBWSgUZEfo3U0ebwXXu65+tcY/jGaNisnDaOMkKBqkLPSj2ey/7vGcP53cnualiZTEySSGsgSx01Z3EVQni5GeDYSMcGuUER4I32tl/N8j58HgNqplvdPuf9Wo0JfrReNKgZLeqciMObrbikYx0pMF8t2ta8TFgokCQ=,iv:caJ2sGL9xzSNEMiPebpvgDwdI1sqbLPOaGmh+YmehUU=,tag:Fqpw5fnSw4bnUF8M+SDIVQ==,type:str]
    encrypted_regex: ((?i)(displayname|email|pass|ca|id|bootstraptoken|secretboxencryptionsecret|secrets|secrets|password|cert|secret($|[^N])|key|token|^data$|^stringData))
    version: 3.10.2
