apiVersion: v1
kind: ConfigMap
metadata:
  name: litellm-config
  namespace: utilities
data:
  litellm_config.yaml: |
    model_list:
      - model_name: gemini-3-pro-preview
        litellm_params:
          model: gemini/gemini-3-pro-preview
          api_key: ${GEMINI_API_KEY}