---
# yaml-language-server: $schema=https://kubernetes-schemas.pages.dev/helm.toolkit.fluxcd.io/helmrelease_v2.json
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: qbittorrent
  namespace: media
spec:
  interval: 15m
  chart:
    spec:
      chart: app-template
      version: 15.24.40
      sourceRef:
        kind: HelmRepository
        name: truecharts
        namespace: flux-system
      interval: 15m
  timeout: 20m
  maxHistory: 3
  install:
    createNamespace: true
    remediation:
      retries: 3
  upgrade:
    cleanupOnFail: true
    remediation:
      retries: 3
  uninstall:
    keepHistory: false
  values:
    credentials:
      s3v2:
        type: s3
        url: "${S3_MINIO_URL}" #"https://s3.amazonaws.com"
        bucket: "${S3_MINIO_BUCKET_PREFIX}-{{ .Chart.Name }}"
        accessKey: "${S3_MINIO_KEY_ID}"
        secretKey: "${S3_MINIO_SECRET_KEY}"
        encrKey: "${S3_MINIO_SECRET_KEY}"
      s3v3:
        type: s3
        url: "${S3_MINIO_URL_V2}"
        bucket: "${S3_MINIO_BUCKET_PREFIX}-{{ .Chart.Name }}"
        accessKey: "${S3_MINIO_KEY_ID_V2}"
        secretKey: "${S3_MINIO_SECRET_KEY_V2}"
        encrKey: "${S3_MINIO_SECRET_KEY_V2}"
    image:
      repository: binhex/arch-qbittorrentvpn
      pullPolicy: Always
      tag: latest
    securityContext:
      container:
        readOnlyRootFilesystem: false
        runAsNonRoot: false
        allowPrivilegeEscalation: true
        privileged: true
        UMASK: "002"
        runAsUser: 0
        runAsGroup: 0
        PUID: 0
        # capabilities:
          # add:
            # - NET_ADMIN
        pod:
          sysctls:
            - name: net.ipv4.conf.all.src_valid_mark
              value: "1"
    service:
      main:
        ports:
          main:
            port: 10095
      # proxy:
      #   enabled: true
      #   ports:
      #     proxy:
      #       enabled: true
      #       port: 8118
      #       protocol: "http"
      #       targetPort: 8118
    workload:
      main:
        podSpec:
          containers:
            main:
              env:
                VPN_ENABLED: "yes"
                VPN_USER: "${PIA_USER}"
                VPN_PASS: "${PIA_PASS}"
                VPN_PROV: "pia"
                VPN_CLIENT: "wireguard"
                STRICT_PORT_FORWARD: "yes"
                ENABLE_PRIVOXY: "yes"
                LAN_NETWORK: "192.168.0.0/16,172.16.0.0/16,172.17.0.0/16"
                NAME_SERVERS: "84.200.69.80,37.235.1.174,1.1.1.1,37.235.1.177,84.200.70.40,1.0.0.1"
                VPN_INPUT_PORTS: "6881"
                VPN_OUTPUT_PORTS: "6881"
                DEBUG: "false"
                WEBUI_PORT: "{{ .Values.service.main.ports.main.port }}"
    ingress:
      main:
        enabled: true
        ingressClassName: internal
        hosts:
          - host: qbittorrent.${DOMAIN_0}
            paths:
              - path: /
                pathType: Prefix
        tls:
          - hosts:
              - qbittorrent.${DOMAIN_0}
            clusterIssuer: domain-0-le-prod
        integrations:
          traefik:
            enabled: false
          certManager:
            enabled: true
            certificateIssuer: domain-0-le-prod

    persistence:
      config:
        enabled: true
        type: pvc
        mountPath: /config
        targetSelectAll: true
        volsync:
          - name: config
            type: restic
            credentials: s3v3
            dest:
              enabled: true
            src:
              enabled: true
      plex-media:
        enabled: true
        existingClaim: plex-media-pvc
        mountPath: /mnt